import { useEffect, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Search } from 'lucide-react';
import { EmptyState, PageHeader } from './ui';
import './audit.css';

type Event = { id: string; timestamp: string; actor_username: string; actor_user_id?: string; action: string; resource_type: string; resource_name: string; resource_id?: string; server_id?: string; result: string; remote_ip: string; metadata?: unknown; error_code: string; error_summary: string };
export const auditActionLabel = (action: string) => ({ 'server.start': 'Server started', 'server.stop': 'Server stopped', 'server.restart': 'Server restarted', 'file.upload': 'File uploaded', 'user.password_reset': 'Password reset' }[action] ?? action);
export const auditActor = (username?: string) => username || 'Unauthenticated';
const auditMetadata = (metadata: unknown): string => JSON.stringify(metadata, null, 2) ?? 'null';

export function AuditLog() {
  const [items, setItems] = useState<Event[]>([]), [offset, setOffset] = useState(0), [action, setAction] = useState(''), [result, setResult] = useState(''), [error, setError] = useState('');
  const load = () => fetch(`/api/v1/audit?limit=100&offset=${offset}${action ? `&action=${encodeURIComponent(action)}` : ''}${result ? `&result=${result}` : ''}`, { credentials: 'same-origin' }).then(async response => { if (!response.ok) throw new Error((await response.json().catch(() => null))?.error?.message ?? 'Request failed'); return response.json(); }).then(value => { setItems(value.items); setError(''); }).catch(reason => setError(reason.message));
  useEffect(() => { void load(); }, [offset, action, result]);
  return <section className="audit-page"><PageHeader eyebrow="Security" title="Audit log" description="Review security and administrative activity across this GameNode." /><section className="panel audit-panel"><div className="audit-filters"><label><span>Action</span><span className="input-with-icon"><Search /><input value={action} onChange={event => { setOffset(0); setAction(event.target.value); }} placeholder="Filter by action…" /></span></label><label>Result<select value={result} onChange={event => { setOffset(0); setResult(event.target.value); }}><option value="">All results</option><option value="success">Success</option><option value="failure">Failure</option></select></label></div>{error && <p className="error notice">{error}</p>}{!error && items.length === 0 ? <EmptyState title="No audit events found" description={action || result ? 'Try adjusting the current filters.' : 'Security and administrative activity will appear here.'} icon={Activity} /> : <div className="data-table audit-table"><div className="table-head"><span>Event</span><span>Actor</span><span>Resource</span><span>Time</span><span>Result</span></div>{items.map(item => <article className="table-row" key={item.id}><div><strong>{auditActionLabel(item.action)}</strong><small>{item.action}</small></div><div><strong>{auditActor(item.actor_username)}</strong><small>{item.remote_ip || 'Local'}</small></div><div><span>{item.resource_type}</span><small>{item.resource_name || item.resource_id || '—'}</small></div><time>{new Date(item.timestamp).toLocaleString()}</time><span className={`status ${item.result === 'failure' ? 'crashed' : 'running'}`}>{item.result}</span>{item.error_summary && <p className="error audit-detail">{item.error_summary}</p>}{item.metadata !== undefined && <details className="audit-detail"><summary>Metadata</summary><pre>{auditMetadata(item.metadata)}</pre></details>}</article>)}</div>}<footer className="pagination"><span>Showing {items.length ? offset + 1 : 0}–{offset + items.length}</span><div><button className="quiet" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 100))}><ArrowLeft />Previous</button><button className="quiet" disabled={items.length < 100} onClick={() => setOffset(offset + 100)}>Next<ArrowRight /></button></div></footer></section></section>;
}
