import { FormEvent, useEffect, useRef, useState } from 'react';
import { CircleAlert, Eraser, Send, SquareTerminal } from 'lucide-react';
import { EmptyState } from './ui';
import './console.css';

type Message = { type: string; stream?: string; data?: string; state?: string };
const maxLines = 2000;
const visibleLines = new Map<string, Message[]>();

export function ConsoleTab({ serverID, serverState, canSend = true }: { serverID: string; serverState: string; canSend?: boolean }) {
  const [lines, setLines] = useState<Message[]>(() => visibleLines.get(serverID) ?? []), [status, setStatus] = useState('connecting'), [command, setCommand] = useState(''), [auto, setAuto] = useState(true);
  const socket = useRef<WebSocket | null>(null), view = useRef<HTMLDivElement>(null);
  const disabled = !canSend || serverState === 'stopped' || serverState === 'crashed' || status === 'detached' || status === 'closed';
  useEffect(() => { let closed = false, terminal = false, tries = 0, timer = 0; const connect = () => { const ws = new WebSocket(`${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/api/v1/servers/${serverID}/console/ws`); socket.current = ws; ws.onopen = () => { tries = 0; setStatus('connected'); }; ws.onmessage = event => { try { const message = JSON.parse(event.data) as Message; if (message.type === 'console') { const state=message.state ?? 'closed'; setStatus(state); terminal=state==='closed'||state==='detached'; } else { setLines(value => { const next = [...value, message].slice(-maxLines); visibleLines.set(serverID, next); return next }); if (message.type==='state'&&message.state&&message.state!=='running') { setStatus(message.state); terminal=true; } } } catch {} }; ws.onclose = () => { if (!closed && !terminal && tries < 5) { setStatus('disconnected'); timer = window.setTimeout(connect, Math.min(1000 * 2 ** tries++, 10000)); } }; }; connect(); return () => { closed = true; window.clearTimeout(timer); socket.current?.close(); }; }, [serverID]);
  useEffect(() => { if (auto) view.current?.scrollTo({ top: view.current.scrollHeight }); }, [lines, auto]);
  function send(event: FormEvent) { event.preventDefault(); if (!command || disabled || socket.current?.readyState !== WebSocket.OPEN) return; socket.current.send(JSON.stringify({ type: 'input', data: command.endsWith('\n') ? command : `${command}\n` })); setCommand(''); }
  if (status === 'detached') return <section className="console-panel"><EmptyState title="Console is detached" description="This process was rediscovered after GameNode restarted. Restart the server through GameNode to restore console attachment." icon={CircleAlert} /></section>;
  return <section className="console-panel"><header className="console-toolbar"><div><span className="console-title"><SquareTerminal />Live console</span><small>Plain-text process output</small></div><span className={`connection-state connection-state--${status}`}>{status} · {serverState}{!canSend && ' · read-only'}</span></header><div className="console-output" ref={view}>{lines.length === 0 ? <div className="console-empty"><SquareTerminal /><span>Waiting for process output…</span></div> : lines.map((line, index) => <div key={index} className={`console-line ${line.stream ?? ''}`}>{line.data ?? line.state ?? ''}</div>)}</div><div className="console-controls"><label><input type="checkbox" checked={auto} onChange={event => setAuto(event.target.checked)} /> Follow output</label><button type="button" className="quiet" onClick={() => setLines([])}><Eraser />Clear view</button></div><form className="console-input" onSubmit={send}><span className="console-prompt" aria-hidden="true">›</span><input aria-label="Console command" value={command} onChange={event => setCommand(event.target.value)} disabled={disabled} placeholder={disabled ? (canSend ? 'Console input unavailable' : 'Read-only console') : 'Enter a command…'} /><button disabled={disabled || !command}><Send />Send</button></form></section>;
}
