import {FormEvent,useEffect,useState} from 'react';
import {SectionHeader} from './ui';
import {gameConfigAdapterSource,gameConfigInputType,gameConfigPayload,initialGameConfigValues,type GameConfigField} from './game-configuration-helpers';
import './game-configuration.css';

type Field=GameConfigField&{label:string;description?:string;section?:string};
type Adapter={id:string;version:string;format:string;target:string;restart_required:boolean;ready:boolean;status_message?:string;fields:Field[]};
type Result={available:boolean;adapters:Adapter[]};
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(init?.headers??{})},...init});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message??'Request failed')}return response.json()}

export function GameConfiguration({serverID,token,canEdit,canRestart,onRestart}:{serverID:string;token:string;canEdit:boolean;canRestart?:boolean;onRestart?:()=>void}){
 const [result,setResult]=useState<Result>();const [values,setValues]=useState<Record<string,Record<string,string>>>({});const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);
 useEffect(()=>{request<Result>(`/servers/${serverID}/configuration`).then(data=>{setResult(data);setValues(Object.fromEntries(data.adapters.map(adapter=>[adapter.id,initialGameConfigValues(adapter.fields)])))}).catch(reason=>setError(reason.message))},[serverID]);
 async function save(event:FormEvent,adapter:Adapter){event.preventDefault();setBusy(true);setError('');setSaved(false);try{const updated=await request<Result>(`/servers/${serverID}/configuration`,{method:'PUT',headers:{'X-CSRF-Token':token},body:JSON.stringify({adapter_id:adapter.id,values:gameConfigPayload(adapter.fields,values[adapter.id]??{})})});setResult(updated);setValues(Object.fromEntries(updated.adapters.map(item=>[item.id,initialGameConfigValues(item.fields)])));setSaved(true)}catch(reason){setError(reason instanceof Error?reason.message:'Configuration could not be saved')}finally{setBusy(false)}}
 if(error&&!result)return <p className="error notice">{error}</p>;
 if(!result)return <p className="notice">Loading managed game configuration…</p>;
 if(!result.available)return <p className="muted">This server has no versioned GameNode configuration adapter. Its files remain available through the Files tab.</p>;
 return <div className="game-config-list">{error&&<p className="error notice">{error}</p>}{saved&&<div className="notice"><strong>Configuration saved.</strong><br />Restart required for changes to take effect.{canRestart&&onRestart&&<><br /><button className="quiet" type="button" onClick={onRestart}>Restart server</button></>}</div>}{result.adapters.map(adapter=><form className="subpanel form-panel" key={adapter.id} onSubmit={event=>save(event,adapter)}><SectionHeader title="Game settings" description={gameConfigAdapterSource(adapter)}/>{!adapter.ready&&<p className="notice">{adapter.status_message??'The game has not generated this configuration file yet.'}</p>}{[...new Set(adapter.fields.map(field=>field.section||'General'))].map(section=><fieldset disabled={!adapter.ready} key={section}><legend>{section}</legend>{adapter.fields.filter(field=>(field.section||'General')===section).map(field=><label key={field.key}>{field.label}{field.required?' *':''}{field.validation.allowed?.length?<select disabled={!canEdit||!adapter.ready} value={values[adapter.id]?.[field.key]??''} onChange={event=>setValues({...values,[adapter.id]:{...values[adapter.id],[field.key]:event.target.value}})}>{field.validation.allowed.map(value=><option key={value}>{value}</option>)}</select>:gameConfigInputType(field)==='checkbox'?<input disabled={!canEdit||!adapter.ready} type="checkbox" checked={['true','1'].includes(values[adapter.id]?.[field.key]??'')} onChange={event=>setValues({...values,[adapter.id]:{...values[adapter.id],[field.key]:event.target.checked?'true':'false'}})}/>:<input disabled={!canEdit||!adapter.ready} type={gameConfigInputType(field)} value={values[adapter.id]?.[field.key]??''} min={field.validation.min} max={field.validation.max} minLength={field.validation.min_length} maxLength={field.validation.max_length} required={adapter.ready&&field.required&&!field.sensitive} placeholder={field.sensitive&&field.configured?'Configured · leave empty to keep current value':''} onChange={event=>setValues({...values,[adapter.id]:{...values[adapter.id],[field.key]:event.target.value}})}/>}<small>{field.description}{field.sensitive&&field.configured?' This secret is configured and is never returned by the API.':''}</small></label>)}</fieldset>)}{adapter.restart_required&&<p className="notice">Changes require a server restart. GameNode will not restart it automatically.</p>}{canEdit&&<button disabled={busy||!adapter.ready}>{busy?'Saving…':'Save game settings'}</button>}</form>)}</div>
}
