import { FormEvent, useCallback, useEffect, useState, type ChangeEvent } from 'react';
import { Activity, ArrowDownToLine, ArrowUp, File, FilePlus2, Folder, FolderPlus, RefreshCw, Send, Server as ServerIcon, SquareTerminal, Trash2, Upload } from 'lucide-react';
import { EmptyState, LoadingState, SectionHeader } from './ui';
import { isSafeRelativePath, joinRelativePath, parentRelativePath } from './files-helpers';
import type { RemoteNode } from './nodes-helpers';
import { hasRemotePermission, remoteBytes, remotePath, remoteServerStateLabel, remoteServerStateTone } from './remote-servers-helpers';
import './remote-servers.css';

type RemoteRuntime = { pid?: number; current_state: string; last_error?: string; console_detached?: boolean; crash_count?: number; restart_count?: number };
export type RemoteServer = { id: string; tenant_id: string; tenant_name?: string; name: string; description?: string; creation_mode: string; runtime_type: string; auto_start: boolean; restart_policy: string; created_at: string; updated_at: string; runtime: RemoteRuntime };
type RemoteServerEnvelope = { server: RemoteServer; tenant_name?: string; node_id?: string };
type RemoteFile = { name: string; path: string; type: 'file' | 'directory'; size: number; modified_at: string; is_symlink?: boolean };
type RemoteConsole = { state: string; events: { type: string; stream?: string; data?: string; timestamp: string }[] };
type RemoteMonitoring = { status: string; cpu_percent: number; memory_bytes: number; memory_percent?: number; uptime_seconds?: number };
type ServerDraft = { tenant_id: string; name: string; description: string; working_directory: string; executable: string; arguments: string; runtime_type: string; auto_start: boolean; restart_policy: string; stop_method: string; stop_command: string; stop_timeout_seconds: string };

const emptyDraft: ServerDraft = { tenant_id: '', name: '', description: '', working_directory: '', executable: '', arguments: '', runtime_type: 'native', auto_start: false, restart_policy: 'never', stop_method: 'terminate', stop_command: '', stop_timeout_seconds: '30' };

async function remoteAPI<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/v1${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(init?.method && init.method !== 'GET' ? { 'X-CSRF-Token': token } : {}), ...(init?.headers ?? {}) }, ...init });
  if (!response.ok) {
    const body = await response.json().catch(() => null);
    throw new Error(body?.error?.message ?? (response.status === 501 ? 'This remote node does not support the requested operation.' : 'Remote request failed.'));
  }
  return response.status === 204 ? undefined as T : response.json();
}

const errorMessage = (reason: unknown) => reason instanceof Error ? reason.message : 'Remote request failed.';
const serverPath = (nodeID: string, serverID = '') => `/remote-nodes/${encodeURIComponent(nodeID)}/servers${serverID ? `/${encodeURIComponent(serverID)}` : ''}`;
const formFromServer = (server?: RemoteServer): ServerDraft => server ? { ...emptyDraft, tenant_id: server.tenant_id, name: server.name, description: server.description ?? '', runtime_type: server.runtime_type, auto_start: server.auto_start, restart_policy: server.restart_policy } : { ...emptyDraft };
const unwrapRemoteServer = (envelope: RemoteServerEnvelope): RemoteServer => ({ ...envelope.server, tenant_name: envelope.tenant_name });
const payloadFromDraft = (draft: ServerDraft) => ({ tenant_id: draft.tenant_id.trim(), name: draft.name.trim(), description: draft.description.trim(), working_directory: draft.working_directory.trim(), executable: draft.executable.trim(), arguments: draft.arguments.split('\n').map(value => value.trim()).filter(Boolean), runtime_type: draft.runtime_type, auto_start: draft.auto_start, restart_policy: draft.restart_policy, stop_method: draft.stop_method, stop_command: draft.stop_command.trim(), stop_timeout_seconds: Number(draft.stop_timeout_seconds) || 30 });

export function RemoteServersPanel({ node, token, permissions }: { node: RemoteNode; token: string; permissions?: string[] }) {
  const canView = hasRemotePermission(permissions, 'RemoteServer.View');
  const supported = node.capabilities?.includes('remote_server_management') ?? false;
  const [servers, setServers] = useState<RemoteServer[]>([]); const [selected, setSelected] = useState<RemoteServer>(); const [showCreate, setShowCreate] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!canView || !supported) return; setLoading(true); setError(''); try { setServers(((await remoteAPI<{ remote_servers: RemoteServerEnvelope[] | null }>(serverPath(node.id), token)).remote_servers ?? []).map(unwrapRemoteServer)); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }, [canView, node.id, supported, token]);
  useEffect(() => { void load(); }, [load]);
  if (!canView || !supported) return null;
  if (selected) return <RemoteServerDetail node={node} token={token} permissions={permissions} initial={selected} onBack={() => { setSelected(undefined); void load(); }} onChanged={server => { setSelected(server); void load(); }} onDeleted={() => { setSelected(undefined); void load(); }} />;
  return <section className="detail-card remote-servers-panel"><SectionHeader title="Remote servers" description="Servers remain owned and controlled by the remote node. This controller forwards bounded, permission-checked requests through its Node API." />{error && <p className="error notice">{error}</p>}<div className="actions"><button className="quiet" onClick={() => void load()} disabled={loading}><RefreshCw />{loading ? 'Refreshing…' : 'Refresh'}</button>{hasRemotePermission(permissions, 'RemoteServer.Manage') && <button onClick={() => setShowCreate(true)}><ServerIcon />Add remote server</button>}</div>{showCreate && <RemoteServerForm nodeID={node.id} token={token} onCancel={() => setShowCreate(false)} onSaved={server => { setShowCreate(false); setServers(current => [...current, server]); setSelected(server); }} />}{loading && servers.length === 0 ? <LoadingState label="Loading remote servers" /> : servers.length === 0 ? <EmptyState compact icon={ServerIcon} title="No remote servers visible" description="This node has no servers visible to your current tenant permissions." action={hasRemotePermission(permissions, 'RemoteServer.Manage') ? <button onClick={() => setShowCreate(true)}>Add remote server</button> : undefined} /> : <div className="data-table remote-servers-table"><div className="table-head"><span>Server</span><span>Runtime</span><span>State</span><span>Tenant</span><span>Actions</span></div>{servers.map(server => <div className="table-row" key={server.id}><strong>{server.name}<br /><small>{server.id}</small></strong><span>{server.runtime_type}</span><span className={`status ${remoteServerStateTone(server.runtime.current_state)}`}>{remoteServerStateLabel(server.runtime.current_state)}</span><span>{server.tenant_name || server.tenant_id}</span><span className="table-actions"><button className="quiet" onClick={() => setSelected(server)}>Open</button></span></div>)}</div>}</section>;
}

function RemoteServerForm({ nodeID, token, initial, onCancel, onSaved }: { nodeID: string; token: string; initial?: RemoteServer; onCancel: () => void; onSaved: (server: RemoteServer) => void }) {
  const [draft, setDraft] = useState<ServerDraft>(() => formFromServer(initial)); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const update = <K extends keyof ServerDraft>(key: K, value: ServerDraft[K]) => setDraft(current => ({ ...current, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); if (!draft.name.trim() || (!initial && (!draft.working_directory.trim() || !draft.executable.trim()))) { setError(initial ? 'Name is required.' : 'Name, working directory, and executable are required.'); return; } setSaving(true); setError(''); try { const payload = initial ? { name: draft.name.trim(), description: draft.description.trim(), auto_start: draft.auto_start, restart_policy: draft.restart_policy } : payloadFromDraft(draft); const result = await remoteAPI<RemoteServerEnvelope>(initial ? serverPath(nodeID, initial.id) : serverPath(nodeID), token, { method: initial ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); onSaved(unwrapRemoteServer(result)); } catch (reason) { setError(errorMessage(reason)); } finally { setSaving(false); } }
  return <form className="panel form-panel remote-server-form" onSubmit={save}><SectionHeader title={initial ? 'Edit remote server' : 'Add remote server'} description={initial ? 'Only safe metadata is editable remotely. The remote node keeps its paths, executable, arguments, environment, and stop command private.' : 'The remote node validates and applies this structured native server definition. No local controller process or runtime is started.'} /><div className="form-grid"><label>Tenant ID<input disabled={!!initial} value={draft.tenant_id} onChange={e => update('tenant_id', e.target.value)} /></label><label>Name<input autoFocus value={draft.name} onChange={e => update('name', e.target.value)} required /></label><label>Description<input value={draft.description} onChange={e => update('description', e.target.value)} /></label><label>Working directory<input disabled={!!initial} value={draft.working_directory} onChange={e => update('working_directory', e.target.value)} required={!initial} /></label><label>Executable<input disabled={!!initial} value={draft.executable} onChange={e => update('executable', e.target.value)} required={!initial} /></label><label>Runtime<select disabled={!!initial} value={draft.runtime_type} onChange={e => update('runtime_type', e.target.value)}><option value="native">Native</option></select></label><label>Stop method<select disabled={!!initial} value={draft.stop_method} onChange={e => update('stop_method', e.target.value)}><option value="terminate">Terminate</option><option value="stdin_command">Stdin command</option><option value="console_interrupt">Console interrupt</option></select></label><label>Stop timeout (seconds)<input disabled={!!initial} type="number" min="1" max="300" value={draft.stop_timeout_seconds} onChange={e => update('stop_timeout_seconds', e.target.value)} /></label><label className="full-field">Arguments (one per line)<textarea disabled={!!initial} value={draft.arguments} onChange={e => update('arguments', e.target.value)} rows={4} /></label><label className="full-field">Stop command<input disabled={!!initial} value={draft.stop_command} onChange={e => update('stop_command', e.target.value)} /></label><label><input type="checkbox" checked={draft.auto_start} onChange={e => update('auto_start', e.target.checked)} /> Auto-start</label></div>{error && <p className="error notice">{error}</p>}<div className="actions"><button disabled={saving}>{saving ? 'Saving…' : initial ? 'Save changes' : 'Create server'}</button><button type="button" className="quiet" onClick={onCancel} disabled={saving}>Cancel</button></div></form>;
}

function RemoteServerDetail({ node, token, permissions, initial, onBack, onChanged, onDeleted }: { node: RemoteNode; token: string; permissions?: string[]; initial: RemoteServer; onBack: () => void; onChanged: (server: RemoteServer) => void; onDeleted: () => void }) {
  const [server, setServer] = useState(initial); const [tab, setTab] = useState<'overview' | 'console' | 'files' | 'monitoring'>('overview'); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const canManage = hasRemotePermission(permissions, 'RemoteServer.Manage');
  const lifecycle = async (action: 'start' | 'stop' | 'restart' | 'kill') => { setBusy(action); setError(''); try { const result = await remoteAPI<RemoteServerEnvelope>(`${serverPath(node.id, server.id)}/${action}`, token, { method: 'POST', body: '{}' }); const updated = unwrapRemoteServer(result); setServer(updated); onChanged(updated); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(''); } };
  const remove = async () => { if (!confirm(`Delete remote server ${server.name}? This is executed on the remote node and cannot be undone.`)) return; setBusy('delete'); setError(''); try { await remoteAPI<void>(serverPath(node.id, server.id), token, { method: 'DELETE' }); onDeleted(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(''); } };
  if (editing) return <section className="remote-detail"><RemoteServerForm nodeID={node.id} token={token} initial={server} onCancel={() => setEditing(false)} onSaved={updated => { setEditing(false); setServer(updated); onChanged(updated); }} /></section>;
  const has = (capability: string) => node.capabilities?.includes(capability) ?? false;
  return <section className="remote-detail"><div className="row"><div><p className="eyebrow">Remote server · {server.runtime_type}</p><h2>{server.name}</h2><p className="muted">{node.display_name} · {server.tenant_name || server.tenant_id}</p></div><button className="quiet" onClick={onBack}>Back to node</button></div><p><span className={`status ${remoteServerStateTone(server.runtime.current_state)}`}>{remoteServerStateLabel(server.runtime.current_state)}</span>{server.runtime.pid ? ` PID ${server.runtime.pid}` : ''}</p>{error && <p className="error notice">{error}</p>}<nav className="detail-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Overview</button>{has('remote_console') && hasRemotePermission(permissions, 'RemoteConsole.View') && <button className={tab === 'console' ? 'active' : ''} onClick={() => setTab('console')}>Console</button>}{has('remote_files') && hasRemotePermission(permissions, 'RemoteFiles.View') && <button className={tab === 'files' ? 'active' : ''} onClick={() => setTab('files')}>Files</button>}{has('remote_monitoring') && hasRemotePermission(permissions, 'RemoteMonitoring.View') && <button className={tab === 'monitoring' ? 'active' : ''} onClick={() => setTab('monitoring')}>Monitoring</button>}</nav>{tab === 'overview' && <><section className="monitoring"><div><small>Creation mode</small><strong>{server.creation_mode}</strong></div><div><small>Auto-start</small><strong>{server.auto_start ? 'Enabled' : 'Disabled'}</strong></div><div><small>Restarts</small><strong>{server.runtime.restart_count ?? 0}</strong></div><div><small>Crashes</small><strong>{server.runtime.crash_count ?? 0}</strong></div></section>{server.runtime.last_error && <p className="error">{server.runtime.last_error}</p>}<div className="actions">{canManage && <><button disabled={!!busy} onClick={() => void lifecycle('start')}>Start</button><button disabled={!!busy} onClick={() => void lifecycle('stop')}>Stop</button><button disabled={!!busy} onClick={() => void lifecycle('restart')}>Restart</button><button className="danger" disabled={!!busy} onClick={() => void lifecycle('kill')}>Kill</button><button className="quiet" disabled={!!busy} onClick={() => setEditing(true)}>Edit</button><button className="danger quiet" disabled={!!busy} onClick={() => void remove()}><Trash2 />Delete</button></>}</div></>}{tab === 'console' && <RemoteConsoleTab nodeID={node.id} serverID={server.id} token={token} canSend={hasRemotePermission(permissions, 'RemoteConsole.Send')} />}{tab === 'files' && <RemoteFilesTab nodeID={node.id} serverID={server.id} token={token} permissions={permissions} />}{tab === 'monitoring' && <RemoteMonitoringTab nodeID={node.id} serverID={server.id} token={token} />}{busy && busy !== 'delete' && <p className="hint">{busy} request in progress…</p>}<button className="quiet remote-back" onClick={onBack}>Back to remote servers</button></section>;
}

function RemoteConsoleTab({ nodeID, serverID, token, canSend }: { nodeID: string; serverID: string; token: string; canSend: boolean }) {
  const [snapshot, setSnapshot] = useState<RemoteConsole>({ state: 'connecting', events: [] }); const [input, setInput] = useState(''); const [error, setError] = useState(''); const [follow, setFollow] = useState(true); const [live, setLive] = useState(false); const socketRef = useState<{ current?: WebSocket }>({})[0];
  const load = useCallback(async () => { try { setSnapshot(await remoteAPI<RemoteConsole>(`${serverPath(nodeID, serverID)}/console`, token)); setError(''); } catch (reason) { setError(errorMessage(reason)); } }, [nodeID, serverID, token]);
  useEffect(() => { void load(); const scheme = window.location.protocol === 'https:' ? 'wss:' : 'ws:'; const socket = new WebSocket(`${scheme}//${window.location.host}/api/v1${serverPath(nodeID, serverID)}/console/ws`); socketRef.current = socket; socket.onopen = () => { setLive(true); setError(''); }; socket.onmessage = event => { try { const message = JSON.parse(event.data) as { type?: string; state?: string; stream?: string; data?: string; timestamp?: string }; setSnapshot(current => ({ state: message.state ?? current.state, events: message.type === 'console' && message.state ? current.events : [...current.events, { type: message.type ?? 'event', stream: message.stream, data: message.data, timestamp: message.timestamp ?? new Date().toISOString() }].slice(-1000) })); } catch { setError('Remote console returned an invalid message.'); } }; socket.onerror = () => setLive(false); socket.onclose = () => { setLive(false); void load(); }; return () => { socket.close(); socketRef.current = undefined; }; }, [load, nodeID, serverID]);
  useEffect(() => { if (live) return; const timer = window.setInterval(() => void load(), 2500); return () => window.clearInterval(timer); }, [live, load]);
  useEffect(() => { if (follow) document.querySelector<HTMLElement>('.remote-console-output')?.scrollTo({ top: Number.MAX_SAFE_INTEGER }); }, [follow, snapshot]);
  async function send(event: FormEvent) { event.preventDefault(); if (!input.trim()) return; const data = input.endsWith('\n') ? input : `${input}\n`; try { if (live && socketRef.current?.readyState === WebSocket.OPEN) socketRef.current.send(JSON.stringify({ type: 'input', data })); else await remoteAPI<void>(`${serverPath(nodeID, serverID)}/console`, token, { method: 'POST', body: JSON.stringify({ data }) }); setInput(''); if (!live) void load(); } catch (reason) { setError(errorMessage(reason)); } }
  return <section className="remote-tool"><div className="row"><div><h3><SquareTerminal /> Remote console</h3><p className="muted">{live ? 'Live WebSocket relay' : 'Bounded polling fallback'} · {snapshot.state}{!canSend && ' · read-only'}</p></div><button className="quiet" onClick={() => void load()}><RefreshCw />Refresh</button></div>{error && <p className="error notice">{error}</p>}<div className="remote-console-output">{snapshot.events.length === 0 ? <span className="muted">No console events returned.</span> : snapshot.events.map((event, index) => <div className={`console-line ${event.stream ?? ''}`} key={`${event.timestamp}-${index}`}>{event.data ?? event.type}</div>)}</div><label><input type="checkbox" checked={follow} onChange={e => setFollow(e.target.checked)} /> Follow output</label><form className="remote-console-input" onSubmit={send}><input value={input} onChange={e => setInput(e.target.value)} disabled={!canSend} placeholder={canSend ? 'Enter console input…' : 'Read-only console'} /><button disabled={!canSend || !input.trim()}><Send />Send</button></form></section>;
}

function RemoteMonitoringTab({ nodeID, serverID, token }: { nodeID: string; serverID: string; token: string }) {
  const [snapshot, setSnapshot] = useState<RemoteMonitoring>(); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setSnapshot(await remoteAPI<RemoteMonitoring>(`${serverPath(nodeID, serverID)}/monitoring`, token)); setError(''); } catch (reason) { setError(errorMessage(reason)); } }, [nodeID, serverID, token]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 5000); return () => window.clearInterval(timer); }, [load]);
  return <section className="remote-tool"><div className="row"><div><h3><Activity /> Remote monitoring</h3><p className="muted">Bounded live snapshot from the remote node.</p></div><button className="quiet" onClick={() => void load()}><RefreshCw />Refresh</button></div>{error && <p className="error notice">{error}</p>}{snapshot ? <div className="monitoring"><div><small>Status</small><strong>{snapshot.status}</strong></div><div><small>CPU</small><strong>{Number.isFinite(snapshot.cpu_percent) ? `${snapshot.cpu_percent.toFixed(1)}%` : 'Unavailable'}</strong></div><div><small>Memory</small><strong>{remoteBytes(snapshot.memory_bytes)}</strong></div><div><small>Memory %</small><strong>{typeof snapshot.memory_percent === 'number' ? `${snapshot.memory_percent.toFixed(1)}%` : 'Unavailable'}</strong></div><div><small>Uptime</small><strong>{typeof snapshot.uptime_seconds === 'number' ? `${snapshot.uptime_seconds}s` : 'Unavailable'}</strong></div></div> : !error && <LoadingState label="Loading monitoring" />}</section>;
}

function RemoteFilesTab({ nodeID, serverID, token, permissions }: { nodeID: string; serverID: string; token: string; permissions?: string[] }) {
  const [path, setPath] = useState(''); const [entries, setEntries] = useState<RemoteFile[]>([]); const [openPath, setOpenPath] = useState(''); const [content, setContent] = useState(''); const [saved, setSaved] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const can = (permission: 'RemoteFiles.Edit' | 'RemoteFiles.Upload' | 'RemoteFiles.Download' | 'RemoteFiles.Delete' | 'RemoteFiles.Rename') => hasRemotePermission(permissions, permission);
  const load = useCallback(async (nextPath = path) => { setLoading(true); setError(''); try { const result = await remoteAPI<{ entries: RemoteFile[] }>(`${serverPath(nodeID, serverID)}/files?path=${encodeURIComponent(nextPath)}`, token); setEntries(result.entries ?? []); setPath(nextPath); setOpenPath(''); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }, [nodeID, path, serverID, token]);
  useEffect(() => { void load(''); }, [nodeID, serverID]);
  async function open(entry: RemoteFile) { if (entry.type === 'directory') { void load(entry.path); return; } try { const result = await remoteAPI<{ path: string; content: string }>(`${serverPath(nodeID, serverID)}/files/content?path=${encodeURIComponent(entry.path)}`, token); setOpenPath(result.path); setContent(result.content); setSaved(result.content); } catch (reason) { setError(errorMessage(reason)); } }
  async function save() { if (!openPath || content === saved || !can('RemoteFiles.Edit')) return; try { await remoteAPI<void>(`${serverPath(nodeID, serverID)}/files/content`, token, { method: 'PUT', body: JSON.stringify({ path: openPath, content }) }); setSaved(content); void load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function create(kind: 'file' | 'directory') { const name = prompt(kind === 'file' ? 'File name' : 'Folder name'); if (!name) return; const next = joinRelativePath(path, name); if (!isSafeRelativePath(next)) { setError('Use a server-relative path without traversal.'); return; } try { await remoteAPI<void>(`${serverPath(nodeID, serverID)}/files/${kind}`, token, { method: 'POST', body: JSON.stringify({ path: next, ...(kind === 'file' ? { content: '' } : {}) }) }); void load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function remove(entry: RemoteFile) { if (!confirm(`Delete ${entry.name}?`)) return; try { await remoteAPI<void>(`${serverPath(nodeID, serverID)}/files?path=${encodeURIComponent(entry.path)}${entry.type === 'directory' ? '&recursive=true' : ''}`, token, { method: 'DELETE' }); void load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function move(entry: RemoteFile) { const destination = prompt('Destination relative path', entry.path); if (!destination || !isSafeRelativePath(destination)) { if (destination) setError('Use a server-relative path without traversal.'); return; } try { await remoteAPI<void>(`${serverPath(nodeID, serverID)}/files/move`, token, { method: 'POST', body: JSON.stringify({ source: entry.path, destination: remotePath(destination) }) }); void load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !can('RemoteFiles.Upload')) return; const form = new FormData(); form.append('file', file); try { const response = await fetch(`/api/v1${serverPath(nodeID, serverID)}/files/upload?path=${encodeURIComponent(path)}`, { method: 'POST', credentials: 'same-origin', headers: { 'X-CSRF-Token': token }, body: form }); if (!response.ok) throw new Error('Remote upload failed.'); event.target.value = ''; void load(); } catch (reason) { setError(errorMessage(reason)); } }
  async function download(entry: RemoteFile) { if (!can('RemoteFiles.Download')) return; try { const response = await fetch(`/api/v1${serverPath(nodeID, serverID)}/files/download?path=${encodeURIComponent(entry.path)}`, { credentials: 'same-origin' }); if (!response.ok) throw new Error('Remote download failed.'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = entry.name; link.click(); URL.revokeObjectURL(link.href); } catch (reason) { setError(errorMessage(reason)); } }
  return <section className="remote-tool"><div className="row"><div><h3><Folder /> Remote files</h3><p className="muted">Sandboxed text and binary files · current path: <code>/{path}</code></p></div><button className="quiet" onClick={() => void load()}><RefreshCw />Refresh</button></div><div className="remote-files-toolbar"><button className="quiet" disabled={!path} onClick={() => void load(parentRelativePath(path))}><ArrowUp />Up</button>{can('RemoteFiles.Edit') && <><button className="quiet" onClick={() => void create('file')}><FilePlus2 />New file</button><button className="quiet" onClick={() => void create('directory')}><FolderPlus />New folder</button></>}{can('RemoteFiles.Upload') && <label className="button quiet"><Upload />Upload<input hidden type="file" onChange={e => void upload(e)} /></label>}</div>{error && <p className="error notice">{error}</p>}<div className="remote-files-table"><div className="files-header"><span>Name</span><span>Type</span><span>Size</span><span>Modified</span><span>Actions</span></div>{loading ? <LoadingState label="Loading remote files" /> : entries.length === 0 ? <EmptyState compact title="Directory is empty" description="No entries were returned by the remote node." icon={Folder} /> : entries.map(entry => <div className="files-row" key={entry.path}><button className="file-name" onClick={() => void open(entry)}>{entry.type === 'directory' ? <Folder /> : <File />}{entry.name}</button><span>{entry.type}</span><span>{entry.type === 'file' ? remoteBytes(entry.size) : '—'}</span><span>{new Date(entry.modified_at).toLocaleString()}</span><span className="file-actions">{entry.type === 'file' && can('RemoteFiles.Download') && <button className="quiet" onClick={() => void download(entry)}><ArrowDownToLine />Download</button>}{can('RemoteFiles.Rename') && <button className="quiet" onClick={() => void move(entry)}>Move</button>}{can('RemoteFiles.Delete') && <button className="danger quiet" onClick={() => void remove(entry)}><Trash2 />Delete</button>}</span></div>)}</div>{openPath && <section className="remote-editor panel"><div className="row"><div><h3>{openPath}</h3><p className="muted">{content === saved ? 'Saved' : 'Unsaved changes'}</p></div><div className="actions"><button className="quiet" onClick={() => { setOpenPath(''); setContent(''); }}>Close</button>{can('RemoteFiles.Edit') && <button onClick={() => void save()} disabled={content === saved}>Save</button>}</div></div><textarea value={content} onChange={e => setContent(e.target.value)} readOnly={!can('RemoteFiles.Edit')} rows={18} /></section>}</section>;
}
