import { FormEvent, useEffect, useState } from 'react';
import './settings.css';
import { logCategoryKeys, logCategoryLabels, SettingsForm, SettingsResponse, settingsForm, settingsPatch, validBranding, validHistoryLimit, validPasswordLengths, validSampleInterval } from './settings-helpers';
import { applyBranding } from './branding';
import { supportFilename } from './support-helpers';
import { healthTone } from './server-status';
import { defaultBaseColorDark, defaultBaseColorLight, isValidHexColor, type ThemeMode, type UIPreferences } from './theme';
import { processWallpaperFile } from './wallpaper';
import { SkeletonLines } from './ui';

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/v1${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, ...init });
  if (!response.ok) {
    const body = await response.json().catch(() => null);
    throw new Error(body?.error?.message ?? 'Request failed');
  }
  return response.json();
}

export function SettingsPage({ token, canManage, canReadLog, canFlushLog, preferences, onUpdatePreferences }: { token: string; canManage: boolean; canReadLog: boolean; canFlushLog: boolean; preferences: UIPreferences; onUpdatePreferences: (next: Partial<UIPreferences>) => void }) {
  const [current, setCurrent] = useState<SettingsResponse>();
  const [form, setForm] = useState<SettingsForm>({ sampleInterval: '', historyLimit: '', logLevel: 'info', logCategories: Object.fromEntries(logCategoryKeys.map(key => [key, true])) as SettingsForm['logCategories'], logDetailedErrors: false, passwordMinimumLength: '', passwordMaximumLength: '', brandingName: '', brandingSubtitle: '', containerImageAllowlist: 'docker.io, ghcr.io, quay.io' });
	const [favicon, setFavicon] = useState<File>(); const [faviconBusy, setFaviconBusy] = useState(false); const [faviconInputKey, setFaviconInputKey] = useState(0);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [loading, setLoading] = useState(true);
  const load = () => {
    setLoading(true); setError('');
    void request<SettingsResponse>('/settings').then(value => { setCurrent(value); setForm(settingsForm(value)); }).catch(reason => setError(reason instanceof Error ? reason.message : 'Request failed')).finally(() => setLoading(false));
  };
  useEffect(load, []);
  const patch = current ? settingsPatch(current, form) : undefined;
  const passwordLengthsValid = validPasswordLengths(form.passwordMinimumLength, form.passwordMaximumLength);
  const brandingValid = validBranding(form.brandingName, form.brandingSubtitle);
  const valid = validSampleInterval(form.sampleInterval) && validHistoryLimit(form.historyLimit) && passwordLengthsValid && brandingValid;
  async function save(event: FormEvent) {
    event.preventDefault();
    if (!patch || !valid) return;
    setError(''); setNotice('');
    try {
      const value = await request<SettingsResponse>('/settings', { method: 'PATCH', headers: { 'X-CSRF-Token': token }, body: JSON.stringify(patch) });
      setCurrent(value); setForm(settingsForm(value)); applyBranding(value.branding, true); window.dispatchEvent(new CustomEvent('gamenode:branding', { detail: value.branding })); setNotice(patch.monitoring ? 'Settings saved. Restart GameNode to apply monitoring changes.' : 'Settings saved and applied immediately.');
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed'); }
  }
	async function updateFavicon(remove = false) {
		if (!remove && !favicon) return; setFaviconBusy(true); setError(''); setNotice('');
		try { const response = await fetch('/api/v1/settings/favicon', { method: remove ? 'DELETE' : 'PUT', credentials: 'same-origin', headers: { 'X-CSRF-Token': token }, body: remove ? undefined : favicon }); if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.error?.message ?? 'Favicon update failed'); } const value = await response.json() as SettingsResponse; setCurrent(value); setForm(settingsForm(value)); setFavicon(undefined); setFaviconInputKey(key => key + 1); applyBranding(value.branding, true); window.dispatchEvent(new CustomEvent('gamenode:branding', { detail: value.branding })); setNotice(remove ? 'Custom favicon removed.' : 'Custom favicon saved.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Favicon update failed'); } finally { setFaviconBusy(false); }
	}
  if (loading) return <section><h1>Settings</h1><p className="muted">Configure this GameNode instance.</p><section className="panel settings-panel"><SkeletonLines count={5} label="Loading settings…" /></section></section>;
  if (!current) return <section><h1>Settings</h1><section className="panel"><p className="error">{error || 'Settings are unavailable.'}</p><button className="quiet" onClick={load}>Retry</button></section></section>;
  const field = (label: string, description: string, value: string, update: (next: string) => void, min: number, max: number, unit: string, validValue: boolean) => <label className="settings-field">{label}<span className="hint">{description}</span><div className="settings-number"><input id={label.toLowerCase().replaceAll(' ', '-')} type="number" min={min} max={max} step="1" value={value} onChange={event => update(event.target.value)} disabled={!canManage} aria-invalid={!validValue} /><span>{unit}</span></div>{!validValue && <span className="error">Enter a whole number from {min} to {max}.</span>}</label>;
  return <section className="settings-page"><div className="row"><div><h1>Settings</h1><p className="muted">Configure this GameNode instance.</p></div></div><AppearanceSettings preferences={preferences} onUpdate={onUpdatePreferences} /><section className="panel settings-panel"><div className="row"><div><h2>Instance settings</h2><p className="muted">Configure branding, authentication, monitoring, and logging.</p></div>{current.restart_required && <span className="status starting">Restart required</span>}</div><div className="settings-restart" role="note">Monitoring changes take effect after a restart. Branding, password, and logging changes apply immediately.</div><form onSubmit={save} className="settings-form">
    <h3>Branding</h3>
    <label className="settings-field">Instance name<span className="hint">Shown in the sidebar and used as the browser title.</span><input value={form.brandingName} maxLength={64} disabled={!canManage} aria-invalid={!brandingValid} onChange={event => { setForm({ ...form, brandingName: event.target.value }); setNotice(''); }} /></label>
    <label className="settings-field">Instance subtitle<span className="hint">Short description shown below the instance name.</span><input value={form.brandingSubtitle} maxLength={128} disabled={!canManage} aria-invalid={!brandingValid} onChange={event => { setForm({ ...form, brandingSubtitle: event.target.value }); setNotice(''); }} /></label>
    <label className="settings-field settings-favicon">Custom favicon<span className="hint">PNG or ICO, up to 256 KiB. Stored locally; external favicon URLs are not used.</span><input key={faviconInputKey} type="file" accept="image/png,image/x-icon,.ico" disabled={!canManage || faviconBusy} onChange={event => setFavicon(event.target.files?.[0])} /><span className="actions"><button type="button" disabled={!favicon || faviconBusy} onClick={() => void updateFavicon()}>{faviconBusy ? 'Saving…' : 'Upload favicon'}</button>{current.branding.custom_favicon && <button type="button" className="quiet" disabled={faviconBusy} onClick={() => void updateFavicon(true)}>Remove custom favicon</button>}</span></label>
    {!brandingValid && <p className="error">Instance name is required (maximum 64 characters); subtitle allows up to 128 characters.</p>}
    <h3>Monitoring</h3>{field('Sample interval', 'How often GameNode samples server monitoring data.', form.sampleInterval, sampleInterval => { setForm({ ...form, sampleInterval }); setNotice(''); }, 1, 300, 'seconds', validSampleInterval(form.sampleInterval))}{field('History limit', 'Maximum number of in-memory monitoring samples retained per server.', form.historyLimit, historyLimit => { setForm({ ...form, historyLimit }); setNotice(''); }, 1, 10000, 'samples', validHistoryLimit(form.historyLimit))}
    <h3>Password policy</h3>{field('Minimum password length', 'Required for new and reset local account passwords.', form.passwordMinimumLength, passwordMinimumLength => { setForm({ ...form, passwordMinimumLength }); setNotice(''); }, 8, 128, 'characters', passwordLengthsValid)}{field('Maximum password length', 'Upper bound for new and reset local account passwords.', form.passwordMaximumLength, passwordMaximumLength => { setForm({ ...form, passwordMaximumLength }); setNotice(''); }, 8, 256, 'characters', passwordLengthsValid)}{!passwordLengthsValid && <p className="error">The maximum password length must be at least the minimum length.</p>}
    <h3>Logging</h3><label className="settings-field">Log level<span className="hint">Controls which entries are saved to data/log and shown in the application console. This applies immediately.</span><select value={form.logLevel} onChange={event=>{setForm({...form,logLevel:event.target.value as SettingsForm['logLevel']});setNotice('')}} disabled={!canManage}><option value="debug">Debug</option><option value="info">Info</option><option value="warn">Warning</option><option value="error">Error</option></select></label>
    <div className="settings-field settings-log-categories"><span>Log categories</span><span className="hint">Turn off a category to mute its routine entries. Warnings and errors from a muted category are still recorded - this only mutes routine/informational noise, most usefully HTTP access logging.</span><div className="settings-checkbox-grid">{logCategoryKeys.map(key => <label key={key} className="checkbox-field"><input type="checkbox" checked={form.logCategories[key]} disabled={!canManage} onChange={event => { setForm({ ...form, logCategories: { ...form.logCategories, [key]: event.target.checked } }); setNotice(''); }} />{logCategoryLabels[key]}</label>)}</div></div>
    <div className="settings-field"><label className="checkbox-field"><input type="checkbox" checked={form.logDetailedErrors} disabled={!canManage} onChange={event => { setForm({ ...form, logDetailedErrors: event.target.checked }); setNotice(''); }} />Detailed error logging</label><span className="hint">When enabled, the local application log may additionally record the raw underlying error from internal components (for example a database error) alongside the normal sanitized message. This never changes what the API returns or what is written to the audit log or a support bundle - it only affects data/log on this server. Leave this off unless you are actively troubleshooting.</span></div>
    <h3>Container image policy</h3><label className="settings-field">Allowed registries<span className="hint">Comma-separated registry hostnames used by Container servers and Egg provisioning. No registry credentials are stored.</span><textarea rows={2} value={form.containerImageAllowlist} disabled={!canManage} onChange={event => { setForm({ ...form, containerImageAllowlist: event.target.value }); setNotice(''); }} /></label>
    {error && <p className="error">{error}</p>}{notice && <p className="settings-success">{notice}</p>}{canManage && <div className="actions"><button type="submit" disabled={!patch || !valid}>Save changes</button></div>}
  </form></section><EmailAlertSettings token={token} canManage={canManage}/>{canReadLog&&<ApplicationLog/>}{canFlushLog&&<LogMaintenance token={token}/>}<DiagnosticsInfo /><SupportInfo token={token} canManage={canManage}/></section>;
}

type EmailAlertEventKey = 'started'|'stopped'|'crashed'|'restarted'|'auto_restart_failed'|'auto_restart_limit';
type EmailAlertConfiguration = { enabled:boolean;smtp_host:string;smtp_port:number;smtp_security:'starttls'|'tls'|'none';smtp_username:string;password_configured:boolean;from_address:string;recipients:string[];subject_prefix:string;events:Record<EmailAlertEventKey,boolean> };
const emailEventLabels:Record<EmailAlertEventKey,string>={started:'Server started',stopped:'Server stopped',crashed:'Server crashed',restarted:'Server restarted',auto_restart_failed:'Automatic restart failed',auto_restart_limit:'Automatic restart limit reached'};

function EmailAlertSettings({token,canManage}:{token:string;canManage:boolean}) {
  const [value,setValue]=useState<EmailAlertConfiguration>();
  const [form,setForm]=useState<EmailAlertConfiguration & {smtp_password:string;recipients_text:string}>();
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=()=>{setError('');void request<EmailAlertConfiguration>('/settings/email-alerts').then(next=>{setValue(next);setForm({...next,smtp_password:'',recipients_text:next.recipients.join('\n')})}).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load email alert settings'))};
  useEffect(load,[]);
  if(!form)return <section className="panel settings-panel email-alert-settings"><h2>Email alerts</h2>{error?<><p className="error">{error}</p><button className="quiet" onClick={load}>Retry</button></>:<SkeletonLines count={3} label="Loading email alert settings…"/>}</section>;
  const update=<K extends keyof typeof form>(key:K,next:(typeof form)[K])=>{setForm({...form,[key]:next});setNotice('')};
  const recipients=form.recipients_text.split(/[\n,;]/).map(item=>item.trim()).filter(Boolean);
  const save=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');setNotice('');try{const patch={enabled:form.enabled,smtp_host:form.smtp_host,smtp_port:form.smtp_port,smtp_security:form.smtp_security,smtp_username:form.smtp_username,from_address:form.from_address,recipients,subject_prefix:form.subject_prefix,events:form.events,...(form.smtp_password?{smtp_password:form.smtp_password}:{})};const next=await request<EmailAlertConfiguration>('/settings/email-alerts',{method:'PATCH',headers:{'X-CSRF-Token':token},body:JSON.stringify(patch)});setValue(next);setForm({...next,smtp_password:'',recipients_text:next.recipients.join('\n')});setNotice('Email alert settings saved.')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save email alert settings')}finally{setBusy(false)}};
  const test=async()=>{setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/v1/settings/email-alerts/test',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':token}});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message??'Test email failed')}setNotice('Test email sent.')}catch(reason){setError(reason instanceof Error?reason.message:'Test email failed')}finally{setBusy(false)}};
  const clearPassword=async()=>{setBusy(true);setError('');setNotice('');try{const next=await request<EmailAlertConfiguration>('/settings/email-alerts',{method:'PATCH',headers:{'X-CSRF-Token':token},body:JSON.stringify({clear_password:true})});setValue(next);setForm({...form,password_configured:false,smtp_password:''});setNotice('Stored SMTP password removed.')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to remove password')}finally{setBusy(false)}};
  return <section className="panel settings-panel email-alert-settings"><div className="row"><div><h2>Email alerts</h2><p className="muted">Send configurable lifecycle alerts through your SMTP server. Delivery runs asynchronously and never blocks server lifecycle actions.</p></div>{form.enabled&&<span className="status running">Enabled</span>}</div><form className="settings-form" onSubmit={save}>
    <h3>Delivery</h3>
    <label className="settings-field checkbox-field"><input type="checkbox" checked={form.enabled} disabled={!canManage} onChange={event=>update('enabled',event.target.checked)}/>Enable email alerts</label>
    <label className="settings-field">SMTP host<span className="hint">Hostname or IP address of the outgoing mail server.</span><input value={form.smtp_host} maxLength={253} disabled={!canManage} onChange={event=>update('smtp_host',event.target.value)}/></label>
    <label className="settings-field">SMTP port<span className="hint">Usually 587 for STARTTLS or 465 for implicit TLS.</span><input type="number" min="1" max="65535" value={form.smtp_port} disabled={!canManage} onChange={event=>update('smtp_port',Number(event.target.value))}/></label>
    <label className="settings-field">Connection security<span className="hint">Authentication is accepted only over TLS. Prefer STARTTLS or implicit TLS.</span><select value={form.smtp_security} disabled={!canManage} onChange={event=>update('smtp_security',event.target.value as EmailAlertConfiguration['smtp_security'])}><option value="starttls">STARTTLS</option><option value="tls">Implicit TLS</option><option value="none">None (no authentication)</option></select></label>
    <label className="settings-field">SMTP username<span className="hint">Leave blank when the relay does not require authentication.</span><input autoComplete="off" value={form.smtp_username} maxLength={256} disabled={!canManage} onChange={event=>update('smtp_username',event.target.value)}/></label>
    <label className="settings-field">SMTP password<span className="hint">{value?.password_configured?'A password is stored. Leave blank to keep it.':'No password is stored.'}</span><input type="password" autoComplete="new-password" value={form.smtp_password} maxLength={512} disabled={!canManage} onChange={event=>update('smtp_password',event.target.value)}/>{value?.password_configured&&canManage&&<button type="button" className="quiet" disabled={busy} onClick={()=>void clearPassword()}>Remove stored password</button>}</label>
    <label className="settings-field">From address<span className="hint">Envelope sender and From header, for example gamenode@example.com.</span><input type="email" value={form.from_address} disabled={!canManage} onChange={event=>update('from_address',event.target.value)}/></label>
    <label className="settings-field">Subject prefix<span className="hint">Prepended to every alert subject.</span><input value={form.subject_prefix} maxLength={80} disabled={!canManage} onChange={event=>update('subject_prefix',event.target.value)}/></label>
    <label className="settings-field settings-email-recipients">Recipients<span className="hint">One address per line, up to 20 recipients.</span><textarea rows={4} value={form.recipients_text} disabled={!canManage} onChange={event=>update('recipients_text',event.target.value)}/></label>
    <h3>Events</h3><div className="settings-field settings-log-categories"><span>Send an alert when…</span><span className="hint">Crash and automatic-restart problems are enabled by default. Choose routine lifecycle notifications separately.</span><div className="settings-checkbox-grid">{(Object.keys(emailEventLabels) as EmailAlertEventKey[]).map(key=><label key={key} className="checkbox-field"><input type="checkbox" checked={form.events[key]} disabled={!canManage} onChange={event=>update('events',{...form.events,[key]:event.target.checked})}/>{emailEventLabels[key]}</label>)}</div></div>
    {error&&<p className="error">{error}</p>}{notice&&<p className="settings-success">{notice}</p>}{canManage&&<div className="actions"><button type="submit" disabled={busy}>{busy?'Saving…':'Save email settings'}</button><button type="button" className="quiet" disabled={busy||!value?.smtp_host||!value?.from_address||!value?.recipients.length} onClick={()=>void test()}>Send test email</button></div>}
  </form></section>;
}

const themeOptions: { value: ThemeMode; label: string }[] = [{ value: 'system', label: 'System' }, { value: 'dark', label: 'Dark' }, { value: 'light', label: 'Light' }];

/** Personal appearance preferences: theme, sidebar, and wallpaper. Stored
 * only in this browser's localStorage (see theme.ts) - deliberately kept
 * out of the instance-wide Settings panel above, and visible/editable by
 * every signed-in user regardless of Settings.Manage. */
function AppearanceSettings({ preferences, onUpdate }: { preferences: UIPreferences; onUpdate: (next: Partial<UIPreferences>) => void }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [inputKey, setInputKey] = useState(0);
  async function onFile(file?: File) {
    if (!file) return;
    setBusy(true); setError('');
    try {
      const image = await processWallpaperFile(file);
      onUpdate({ wallpaper: { ...preferences.wallpaper, image, enabled: true } });
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'The image could not be processed.'); }
    finally { setBusy(false); setInputKey(key => key + 1); }
  }
  const removeWallpaper = () => { onUpdate({ wallpaper: { ...preferences.wallpaper, enabled: false, image: null } }); setInputKey(key => key + 1); };
  return <section className="panel settings-panel appearance-settings">
    <div className="row"><div><h2>Appearance</h2><p className="muted">Personal preference for this browser only. Not part of the shared instance settings above.</p></div></div>
    <div className="settings-form appearance-form">
      <h3>Theme</h3>
      <label className="settings-field">Color theme<span className="hint">System follows your OS setting and updates live.</span><div className="segmented-tabs theme-picker" role="group" aria-label="Color theme">{themeOptions.map(option => <button type="button" key={option.value} className={preferences.theme === option.value ? 'active' : ''} aria-pressed={preferences.theme === option.value} onClick={() => onUpdate({ theme: option.value })}>{option.label}</button>)}</div></label>
      <label className="settings-field checkbox-field"><input type="checkbox" checked={preferences.sidebarCollapsed} onChange={event => onUpdate({ sidebarCollapsed: event.target.checked })} />Start with sidebar collapsed</label>
      <h3>Base color</h3>
      <label className="settings-field settings-color-field">Dark mode base color<span className="hint">Tints the background, sidebar, and other UI surfaces used in dark mode.</span><span className="settings-color-input"><input type="color" value={preferences.baseColorDark} onChange={event => onUpdate({ baseColorDark: isValidHexColor(event.target.value) ? event.target.value : preferences.baseColorDark })} /><span className="hint">{preferences.baseColorDark}</span>{preferences.baseColorDark !== defaultBaseColorDark && <button type="button" className="quiet" onClick={() => onUpdate({ baseColorDark: defaultBaseColorDark })}>Reset</button>}</span></label>
      <label className="settings-field settings-color-field">Light mode base color<span className="hint">Tints the background, sidebar, and other UI surfaces used in light mode.</span><span className="settings-color-input"><input type="color" value={preferences.baseColorLight} onChange={event => onUpdate({ baseColorLight: isValidHexColor(event.target.value) ? event.target.value : preferences.baseColorLight })} /><span className="hint">{preferences.baseColorLight}</span>{preferences.baseColorLight !== defaultBaseColorLight && <button type="button" className="quiet" onClick={() => onUpdate({ baseColorLight: defaultBaseColorLight })}>Reset</button>}</span></label>
      <h3>Wallpaper</h3>
      <label className="settings-field checkbox-field"><input type="checkbox" checked={preferences.wallpaper.enabled} disabled={!preferences.wallpaper.image} onChange={event => onUpdate({ wallpaper: { ...preferences.wallpaper, enabled: event.target.checked } })} />Show background wallpaper</label>
      <label className="settings-field settings-favicon">Background image<span className="hint">PNG, JPEG, or WebP, up to 8 MiB. Stored only in this browser; never uploaded, never a remote URL.</span><input key={inputKey} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={event => void onFile(event.target.files?.[0])} /><span className="actions">{busy && <span className="hint">Processing image…</span>}{preferences.wallpaper.image && <button type="button" className="quiet" disabled={busy} onClick={removeWallpaper}>Remove wallpaper</button>}</span></label>
      {preferences.wallpaper.image && <>
        <label className="settings-field">Blur<span className="hint">{preferences.wallpaper.blur}px</span><input type="range" min={0} max={20} value={preferences.wallpaper.blur} onChange={event => onUpdate({ wallpaper: { ...preferences.wallpaper, blur: Number(event.target.value) } })} /></label>
        <label className="settings-field">Dim<span className="hint">{preferences.wallpaper.dim}%, keeps content readable over bright images</span><input type="range" min={0} max={90} value={preferences.wallpaper.dim} onChange={event => onUpdate({ wallpaper: { ...preferences.wallpaper, dim: Number(event.target.value) } })} /></label>
      </>}
      {error && <p className="error">{error}</p>}
    </div>
  </section>;
}

type ApplicationLogResponse={entries:{level:string;line:string}[];limit:number};
export function ApplicationLogPage({token,canRead,canFlush}:{token:string;canRead:boolean;canFlush:boolean}){return <section className="settings-page"><div className="row"><div><h1>Application log</h1><p className="muted">Live output from the current GameNode process.</p></div></div>{canRead&&<ApplicationLog/>}{canFlush&&<LogMaintenance token={token}/>}</section>}
function ApplicationLog(){const[entries,setEntries]=useState<ApplicationLogResponse['entries']>([]),[error,setError]=useState('');const load=()=>void request<ApplicationLogResponse>('/settings/logs').then(result=>{setEntries(result.entries);setError('')}).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load application log'));useEffect(()=>{load();const timer=window.setInterval(load,2000);return()=>window.clearInterval(timer)},[]);return <section className="panel settings-diagnostics application-log"><div className="row"><div><h2>Application log</h2><p className="muted">Current GameNode process only. Updates every two seconds and is cleared on restart.</p></div><button className="quiet" onClick={load}>Refresh</button></div>{error?<p className="error">{error}</p>:entries.length?<pre aria-live="polite">{entries.map((entry,index)=><code key={`${index}-${entry.line}`} className={`application-log__${entry.level.toLowerCase()}`}>{entry.line}{'\n'}</code>)}</pre>:<p className="muted">No application log entries have been recorded in this process yet.</p>}</section>}

function LogMaintenance({token}:{token:string}){const[busy,setBusy]=useState(false),[message,setMessage]=useState('');const clear=async()=>{if(busy||!window.confirm('Delete all GameNode log files? This cannot be undone.'))return;setBusy(true);setMessage('');try{const response=await fetch('/api/v1/settings/logs/clear',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':token}});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message??'Request failed')}setMessage('Log files cleared.')}catch(e){setMessage(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}};return <section className="panel settings-diagnostics"><h2>Logs</h2><p className="muted">Human-readable daily log files are stored in <code>data/log</code>. Only the level tag is color-highlighted in the application console.</p><button className="danger" onClick={clear} disabled={busy}>{busy?'Clearing…':'Clear log files'}</button>{message&&<p className={message==='Log files cleared.'?'settings-success':'error'}>{message}</p>}</section>}

type Diagnostics = { status:string; application:{version?:string;go_version:string;process_started_at:string;uptime_seconds:number};platform:{os:string;arch:string;logical_cpus:number};database:{type:string;schema_version?:string;healthy:boolean};monitoring:{sample_interval_seconds:number;history_limit:number;restart_required:boolean} };
function DiagnosticsInfo(){const[value,setValue]=useState<Diagnostics>();const[error,setError]=useState('');const load=()=>{setError('');void request<Diagnostics>('/diagnostics').then(setValue).catch(e=>setError(e instanceof Error?e.message:'Request failed'))};useEffect(load,[]);if(error)return <section className="panel settings-diagnostics"><h2>System information</h2><p className="error">{error}</p><button className="quiet" onClick={load}>Retry</button></section>;if(!value)return <section className="panel settings-diagnostics"><h2>System information</h2><p className="muted">Loading diagnostics…</p></section>;return <section className="panel settings-diagnostics"><div className="row"><div><h2>System information</h2><p className="muted">Safe local GameNode diagnostics.</p></div><span className={`status ${healthTone(value.status)}`}>{value.status}</span></div><div className="settings-diagnostic-grid"><div><small>GameNode</small><strong>{value.application.version||'Development build'}</strong><span>Uptime {Math.floor(value.application.uptime_seconds/60)} min</span></div><div><small>Platform</small><strong>{value.platform.os} / {value.platform.arch}</strong><span>{value.platform.logical_cpus} logical CPUs</span></div><div><small>Database</small><strong>{value.database.type}</strong><span>Schema {value.database.schema_version||'unavailable'} · {value.database.healthy?'healthy':'degraded'}</span></div><div><small>Monitoring</small><strong>{value.monitoring.sample_interval_seconds}s / {value.monitoring.history_limit} samples</strong><span>{value.monitoring.restart_required?'Restart required':'Current runtime configuration'}</span></div></div></section>}
function SupportInfo({token,canManage}:{token:string;canManage:boolean}){const[busy,setBusy]=useState(false),[message,setMessage]=useState('');const generate=async()=>{if(busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/v1/support/bundle',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':token}});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.error?.message??'Request failed')}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=supportFilename(r.headers.get('Content-Disposition'));a.click();URL.revokeObjectURL(url);setMessage('Support bundle generated.')}catch(e){setMessage(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}};return <section className="panel settings-diagnostics"><h2>Support</h2><p className="muted">Generate a sanitized support bundle for troubleshooting. It includes diagnostics, safe settings, recent audit activity, and sanitized server summaries. It excludes passwords, server files, console contents, raw logs, and database files.</p>{canManage&&<button onClick={generate} disabled={busy}>{busy?'Generating…':'Generate support bundle'}</button>}{message&&<p className={message==='Support bundle generated.'?'settings-success':'error'}>{message}</p>}</section>}
