import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, FileJson, Package, RefreshCw, Search, ShieldAlert, Trash2, Upload, WifiOff } from 'lucide-react';
import { hasCapability } from './capabilities';
import { EmptyState, PageHeader, SectionHeader, SkeletonCards } from './ui';
import { catalogStatusLabel, compatibilityLabel, compatibilityTone, filterLibrary, maskTemplateDefault, sourceLabel, validateEggFile, variableTypeLabel, versionLabel, type CompatibilityStatus } from './templates-helpers';
import { TemplateProvisionWizard } from './template-provision';
import { useCreatableTenants } from './tenants';
import './templates.css';

type Finding = { severity: 'info' | 'warning' | 'error'; component: string; code: string; summary: string };
type Variable = { name: string; description?: string; key: string; default_value: string; user_viewable: boolean; user_editable: boolean; type: string; sensitive: boolean; required: boolean; nullable: boolean; validation: { min?: number; max?: number; min_length?:number; max_length?:number; allowed?: string[] }; raw_rules?: string[]; placeholder?:string; advanced?:boolean; group?:string };
type Launch = { executable: string; arguments: string[]; working_root: string; working_directory?:string; resolver?: string; stop_method?: string; stop_command?: string; stop_timeout_seconds?:number };
type Compatibility = { status: CompatibilityStatus; findings: Finding[] };
type ContainerRuntimePlan = { images: string[]; installer_image: string; installer_entrypoint: string; startup_template: string; startup_shell: string; config_operations?: { format:string; target:string; key:string; property?:string; required?:boolean }[]; resource_defaults?: { memory_limit_bytes?:number; cpu_limit_millis?:number; pids_limit?:number; temp_size_bytes?:number } };
type Template = { schema_version?:number;id?: string; name: string; description: string; version?:string;category?:string;minimum_gamenode_version?:string;known_limitations?:string[];tags?:string[];icon?:string; source_type: string; source_identifier?: string; source_format_version?: string; source_metadata: { author?: string; tags?:string[];docker_images?: Record<string, string> }; installer: { type: string; steamcmd?: { app_id: number; validate: boolean; login_mode: string; platform: string; beta_branch_variable?: string; beta_password_variable?: string; install_target: string } }; launch?: Launch; platform_launches?:Record<string,Launch>; ports?:{name:string;protocol:string;port?:number;container_port?:number;variable?:string;offset?:number;required?:boolean;purpose?:string}[]; expected_files?:{path:string;type:'file'|'directory';required:boolean;executable?:boolean;platform?:string}[];config_files?:{path:string;format:string;description?:string}[];requirements?:{type:string;level:'hard'|'informational';value?:string;description:string}[];help?:{summary?:string;notes?:string[]}; variables: Variable[]; compatibility: Compatibility; native_compatibility?: Compatibility; container_compatibility?: Compatibility; container_runtime?: ContainerRuntimePlan; read_only?: boolean; platforms?: string[]; prerequisites?: string[] };
type NeoForgePreview = { executable: string; arguments: string[]; working_directory: string; neoforge_version: string; minecraft_version?: string; platform: string; java_found: boolean; eula_accepted:boolean; stop_command: string; stop_timeout_seconds: number };
type CatalogStatus={source:string;fetched_at?:string;cached:boolean;offline:boolean;last_error?:string;invalid_templates:number};
type CatalogResult={schema_version:number;templates:Template[];status:CatalogStatus};

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/v1${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, ...init });
  if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.error?.message ?? 'Request failed'); }
  return response.status === 204 ? undefined as T : response.json();
}

function CompatibilityBadge({ status }: { status: CompatibilityStatus }) { return <span className={`template-status template-status--${compatibilityTone(status)}`}>{compatibilityLabel(status)}</span>; }
function hasProvisionablePath(template: Template): boolean {
  const native = template.native_compatibility ?? template.compatibility;
  const container = template.container_compatibility?.status;
  return native.status !== 'unsupported' || container === 'compatible' || container === 'partially_compatible';
}

function TemplatePreview({ template }: { template: Template }) {
  const native = template.native_compatibility ?? template.compatibility;
  const container = template.container_compatibility;
  const findings = (compatibility: Compatibility | undefined) => compatibility?.findings.map((finding, index) => <article key={`${finding.code}-${index}`} className={`finding finding--${finding.severity}`}><span>{finding.severity === 'error' ? 'Error' : finding.severity === 'warning' ? 'Warning' : 'Info'}</span><div><strong>{finding.code}</strong><p>{finding.summary}</p></div></article>);
  return <div className="template-preview">
    <section className="subpanel"><SectionHeader title="Template info" description="Validated template provenance and runtime compatibility" /><div className="template-summary"><div><small>Name</small><strong>{template.name}</strong></div><div><small>Source</small><strong>{sourceLabel(template.source_type)}</strong></div><div><small>Version</small><strong>{versionLabel(template.version)}</strong></div><div><small>Native</small><CompatibilityBadge status={native.status} /></div><div><small>Container</small><CompatibilityBadge status={container?.status ?? 'unsupported'} /></div></div><p>{template.description || 'No description provided.'}</p>{template.platforms?.length ? <p className="muted"><strong>Platforms:</strong> {template.platforms.join(' · ')}</p> : null}{template.minimum_gamenode_version ? <p className="muted"><strong>Requires GameNode:</strong> {template.minimum_gamenode_version} or newer</p> : null}</section>
    <section className="subpanel"><SectionHeader title="Native compatibility" description="Structured host-process analysis; this path never executes Egg scripts" /><div className="template-summary"><div><small>Installer</small><strong>{template.installer.type === 'steamcmd' ? `SteamCMD · App ${template.installer.steamcmd?.app_id}` : 'Native'}</strong></div><div><small>Startup</small><strong>{template.launch||Object.keys(template.platform_launches??{}).length ? 'Structured process defined' : 'No safe launch plan'}</strong></div><div><small>Variables</small><strong>{template.variables.length} defined</strong></div><div><small>Ports</small><strong>{template.ports?.length??0} declared</strong></div></div>{Object.entries(template.platform_launches??{}).map(([platform,launch])=><div className="definition-row" key={platform}><span>{platform} launch</span><code>{launch.executable} {launch.arguments.join(' ')}</code></div>)}<div className="finding-list">{findings(native)}</div></section>
    {container && <section className="subpanel"><SectionHeader title="Container compatibility" description="Egg installation runs only in a bounded, unprivileged installer container" /><div className="template-summary"><div><small>Images</small><strong>{template.container_runtime?.images.length ?? 0} declared</strong></div><div><small>Installer image</small><code>{template.container_runtime?.installer_image ?? 'Not declared'}</code></div><div><small>Startup shell</small><code>{template.container_runtime?.startup_shell ?? 'Not declared'}</code></div><div><small>Config operations</small><strong>{template.container_runtime?.config_operations?.length ?? 0}</strong></div></div>{template.container_runtime?.images.length ? <p className="muted"><strong>Allowed image choices:</strong> {template.container_runtime.images.join(' · ')}</p> : null}<div className="finding-list">{findings(container)}</div></section>}
    <section className="subpanel"><SectionHeader title="Variables" description="Typed inputs; grouping and advanced flags are presentation metadata only" /><div className="variable-list">{template.variables.map(variable => <article key={variable.key}><div><strong>{variable.name || variable.key}</strong><code>{variable.key}</code></div><p>{variable.description || 'No description'}</p><div className="variable-meta"><span>{variableTypeLabel(variable.type)}</span>{variable.group&&<span>{variable.group}</span>}{variable.advanced&&<span>Advanced</span>}{variable.required && <span>Required</span>}{variable.nullable && <span>Optional</span>}{variable.sensitive && <span className="sensitive"><ShieldAlert />Sensitive</span>}<span>Default: {maskTemplateDefault(variable.default_value, variable.sensitive)}</span></div></article>)}</div></section>
    {!!template.ports?.length&&<section className="subpanel"><SectionHeader title="Ports" description="Derived from validated values before transactional registration"/><div className="definition-list">{template.ports.map(port=><div className="definition-row" key={`${port.protocol}-${port.name}`}><span>{port.name}</span><strong>{port.protocol.toUpperCase()} {port.variable?`{{${port.variable}}}${port.offset?` + ${port.offset}`:''}`:port.port}{port.required?' required':''}</strong><small>{port.purpose}</small></div>)}</div></section>}
    {!!template.expected_files?.length&&<section className="subpanel"><SectionHeader title="Expected installation artifacts" description="Sandboxed paths verified before server registration"/><div className="definition-list">{template.expected_files.map(file=><div className="definition-row" key={`${file.platform??'all'}-${file.path}`}><code>{file.path}</code><strong>{file.type}{file.executable?' executable':''}{file.required?' required':' optional'}{file.platform?` ${file.platform}`:''}</strong></div>)}</div></section>}
    {!!template.requirements?.length&&<section className="subpanel"><SectionHeader title="Typed requirements" description="Hard checks are enforced when determinable; hints remain informational"/>{template.requirements.map((item,index)=><p key={`${item.type}-${index}`}><strong>{item.level==='hard'?'Required':'Information'}: {item.type}</strong><br/>{item.description}</p>)}</section>}
    {(template.config_files?.length||template.help)&&<section className="subpanel"><SectionHeader title="Configuration & help" description="Metadata only; it does not enable arbitrary file edits"/>{template.help?.summary&&<p>{template.help.summary}</p>}{template.config_files?.map(file=><div className="definition-row" key={file.path}><code>{file.path}</code><strong>{file.format}</strong><small>{file.description}</small></div>)}</section>}
    {(template.prerequisites?.length || template.known_limitations?.length) ? <section className="subpanel"><SectionHeader title="Requirements & limitations" description="Review before creating a server" />{template.prerequisites?.length ? <><strong>Requirements</strong><ul>{template.prerequisites.map(item => <li key={item}>{item}</li>)}</ul></> : null}{template.known_limitations?.length ? <><strong>Known limitations</strong><ul>{template.known_limitations.map(item => <li key={item}>{item}</li>)}</ul></> : null}</section> : null}
  </div>;
}

function NeoForgeAdopt({ template, token, onBack, onOpenServer }: { template: Template; token: string; onBack: () => void; onOpenServer: (id: string) => void }) {
  const [serverName,setServerName]=useState('Minecraft NeoForge'); const [root,setRoot]=useState(''); const [min,setMin]=useState('1024'); const [max,setMax]=useState('4096'); const [nogui,setNogui]=useState(true); const [preview,setPreview]=useState<NeoForgePreview>(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const body=()=>({server_name:serverName,server_root:root,minimum_memory_mb:Number(min),maximum_memory_mb:Number(max),nogui});
  async function analyze(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{setPreview(await request<NeoForgePreview>(`/templates/${template.id}/resolve`,{method:'POST',body:JSON.stringify(body())}));}catch(reason){setError(reason instanceof Error?reason.message:'NeoForge analysis failed');}finally{setBusy(false);}}
  async function adopt(){setBusy(true);setError('');try{const record=await request<{server:{id:string}}>(`/templates/${template.id}/adopt`,{method:'POST',headers:{'X-CSRF-Token':token},body:JSON.stringify(body())});onOpenServer(record.server.id);}catch(reason){setError(reason instanceof Error?reason.message:'Server creation failed');}finally{setBusy(false);}}
  return <section><PageHeader eyebrow={sourceLabel(template.source_type)} title="Adopt Minecraft NeoForge" description="Choose an existing installer-generated NeoForge server directory. GameNode only inspects launcher files; it does not download, overwrite, or execute scripts." actions={<button className="quiet" onClick={onBack}><ArrowLeft />Back</button>} />{error&&<p className="error notice">{error}</p>}<form className="panel form-panel" onSubmit={analyze}><label>Server name<input value={serverName} onChange={event=>setServerName(event.target.value)} required /></label><label>Existing server directory<input value={root} onChange={event=>setRoot(event.target.value)} placeholder="C:\\servers\\neoforge" required /></label><div className="form-grid"><label>Minimum memory (MiB)<input type="number" min="256" value={min} onChange={event=>setMin(event.target.value)} required /></label><label>Maximum memory (MiB)<input type="number" min="512" value={max} onChange={event=>setMax(event.target.value)} required /></label></div><label className="checkbox"><input type="checkbox" checked={nogui} onChange={event=>setNogui(event.target.checked)} />Disable Minecraft graphical console (nogui)</label><button disabled={busy}>{busy?'Analyzing…':'Analyze installation'}</button></form>{preview&&<section className="subpanel"><SectionHeader title="Safe launch preview" description="Direct Java process derived from the installed launcher" /><div className="definition-list"><div className="definition-row"><span>NeoForge</span><strong>{preview.neoforge_version}</strong></div><div className="definition-row"><span>Minecraft</span><strong>{preview.minecraft_version||'Not declared'}</strong></div><div className="definition-row"><span>Platform</span><strong>{preview.platform}</strong></div><div className="definition-row"><span>Java</span><code>{preview.java_found?preview.executable:'Not found in JAVA_HOME or PATH'}</code></div><div className="definition-row"><span>Arguments</span><code>{preview.arguments.join(' ')}</code></div><div className="definition-row"><span>Stop</span><code>{preview.stop_command} · {preview.stop_timeout_seconds}s</code></div></div>{!preview.java_found&&<p className="notice notice--warning">Install Java and expose it through JAVA_HOME or PATH before creating the server.</p>}<button onClick={adopt} disabled={busy||!preview.java_found}>Create server</button></section>}</section>;
}

function LegacyTemplatesPage({ token, capabilities, onOpenServer }: { token: string; capabilities?: string[]; onOpenServer?: (id: string) => void }) {
  const canView = hasCapability(capabilities, 'Templates.View'), canManage = hasCapability(capabilities, 'Templates.Manage'), canCreateAdopt = hasCapability(capabilities, 'Server.Create');
  const { tenants: creatableTenants } = useCreatableTenants();
  const canCreateManaged = canCreateAdopt || creatableTenants.length > 0;
  const [items, setItems] = useState<Template[]>([]), [preview, setPreview] = useState<Template>(), [source, setSource] = useState<unknown>(), [selected, setSelected] = useState<Template>(), [wizard, setWizard] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [provisioning,setProvisioning]=useState(false);
  const load = () => canView ? request<{ templates: Template[] }>('/templates').then(result => setItems(result.templates.filter(item=>item.source_type!=='official'&&item.source_type!=='builtin'))).catch(reason => setError(reason.message)) : Promise.resolve();
  useEffect(() => { load(); }, [canView]);
  async function upload(event: ChangeEvent<HTMLInputElement>) { setError(''); setPreview(undefined); setSource(undefined); const file = event.target.files?.[0]; if (!file) return; const validation = validateEggFile(file.name, file.size); if (validation) { setError(validation); return; } try { const parsed = JSON.parse(await file.text()); setSource(parsed); setBusy(true); setPreview(await request<Template>('/templates/analyze/egg', { method: 'POST', headers: { 'X-CSRF-Token': token }, body: JSON.stringify({ egg: parsed }) })); } catch (reason) { setError(reason instanceof SyntaxError ? 'The selected file is not valid JSON.' : reason instanceof Error ? reason.message : 'Egg analysis failed'); } finally { setBusy(false); } }
  async function importTemplate() { if (!source) return; try { setBusy(true); await request<Template>('/templates/import/egg', { method: 'POST', headers: { 'X-CSRF-Token': token }, body: JSON.stringify({ egg: source }) }); setWizard(false); setPreview(undefined); setSource(undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Import failed'); } finally { setBusy(false); } }
  async function remove(template: Template) { if (!template.id) return; try { await request<void>(`/templates/${template.id}`, { method: 'DELETE', headers: { 'X-CSRF-Token': token } }); setSelected(undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Delete failed'); } }
  if (wizard) return <section><PageHeader eyebrow="Templates" title="Import Egg" description="Analyze a Pelican/Pterodactyl Egg before storing a native GameNode template." actions={<button className="quiet" onClick={() => { setWizard(false); setPreview(undefined); setSource(undefined); }}><ArrowLeft />Back</button>} />{error && <p className="error notice">{error}</p>}<section className="panel template-upload"><FileJson /><div><h2>Upload Egg JSON</h2><p>Maximum 256 KiB. Files are analyzed locally by GameNode; URL import is not supported.</p></div><label className="upload-button"><Upload />Choose JSON<input type="file" accept="application/json,.json" onChange={upload} disabled={busy} /></label></section>{busy && <p className="notice">Analyzing Egg…</p>}{preview && <><TemplatePreview template={preview} /><div className="template-import-actions"><button className="quiet" onClick={() => { setPreview(undefined); setSource(undefined); }}>Choose another file</button><button onClick={importTemplate} disabled={busy}><Package />Import template</button></div></>}</section>;
  const openServer=onOpenServer ?? ((id:string) => { sessionStorage.setItem('gamenode:open-server', id); window.dispatchEvent(new Event('gamenode:open-server')); });
  if (selected && provisioning && selected.source_type==='builtin') return <NeoForgeAdopt template={selected} token={token} onBack={()=>setProvisioning(false)} onOpenServer={openServer} />;
  if (selected && provisioning) return <TemplateProvisionWizard template={selected} token={token} capabilities={capabilities} tenants={creatableTenants} onBack={() => setProvisioning(false)} onOpenServer={openServer} />;
  if (selected) return <section><PageHeader eyebrow={selected.source_type==='builtin'?'Built-in template':'Imported Egg'} title={selected.name} description={selected.description || 'Game template'} actions={<><button className="quiet" onClick={() => setSelected(undefined)}><ArrowLeft />Back</button>{canView && (selected.source_type==='builtin' ? canCreateAdopt : canCreateManaged) && hasProvisionablePath(selected) && <button onClick={() => setProvisioning(true)}>Create server</button>}{canManage && !selected.read_only && <button className="danger quiet" onClick={() => remove(selected)}><Trash2 />Delete</button>}</>} /><TemplatePreview template={selected} /></section>;
  return <section><PageHeader eyebrow="Personal" title="Imported templates" description="Normalized Pelican/Pterodactyl Egg imports stored in GameNode." actions={canManage ? <button onClick={() => { setWizard(true); setError(''); }}><Upload />Import Egg</button> : undefined} />{error && <p className="error notice">{error}</p>}{!canView ? <EmptyState icon={Package} title="Import access only" description="You may analyze and import Eggs, but Templates.View is required to list stored templates." action={canManage ? <button onClick={() => setWizard(true)}>Import Egg</button> : undefined} /> : items.length === 0 ? <EmptyState icon={Package} title="No imported templates" description="Import a Pelican/Pterodactyl Egg to create a personal template." /> : <div className="template-grid">{items.map(template => <button key={template.id} className="template-card" onClick={() => setSelected(template)}><span className="template-card__icon"><Package /></span><span><strong>{template.name}</strong><small>Imported Egg · {template.platforms?.join(' / ') || template.installer.type}</small></span><span className="template-card__compatibility"><CompatibilityBadge status={(template.native_compatibility??template.compatibility).status}/>{template.container_compatibility&&<CompatibilityBadge status={template.container_compatibility.status}/>}</span></button>)}</div>}</section>;
}

export function TemplatesPage({ token, capabilities, onOpenServer }: { token: string; capabilities?: string[]; onOpenServer?: (id: string) => void }) {
  const canView=hasCapability(capabilities,'Templates.View'),canManage=hasCapability(capabilities,'Templates.Manage'),canCreateAdopt=hasCapability(capabilities,'Server.Create');
  // Ordinary managed templates (SteamCMD/native, installed under GameNode's
  // managed tenant storage) may be provisioned by anyone holding Server.Create
  // in at least one tenant, not only a global grant - see useCreatableTenants.
  // The NeoForge adopt resolver accepts an arbitrary host directory, so it
  // stays global-Server.Create-only like the Custom/Adopt server form.
  const { tenants: creatableTenants } = useCreatableTenants();
  const canCreateManaged = canCreateAdopt || creatableTenants.length > 0;
  const [catalog,setCatalog]=useState<CatalogResult>({schema_version:1,templates:[],status:{source:'none',cached:false,offline:false,invalid_templates:0}});
  const [personal,setPersonal]=useState<Template[]>([]),[selected,setSelected]=useState<Template>(),[provisioning,setProvisioning]=useState(false),[manage,setManage]=useState(false);
  const [query,setQuery]=useState(''),[source,setSource]=useState('all'),[category,setCategory]=useState('all'),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
  const openServer=onOpenServer ?? ((id:string)=>{sessionStorage.setItem('gamenode:open-server',id);window.dispatchEvent(new Event('gamenode:open-server'));});
  async function load(){if(!canView){setLoading(false);return;}try{const [remote,all]=await Promise.all([request<CatalogResult>('/template-catalog'),request<{templates:Template[]}>('/templates')]);setCatalog(remote);setPersonal(all.templates.filter(item=>item.source_type!=='official'));}catch(reason){setError(reason instanceof Error?reason.message:'Game Library could not be loaded');}finally{setLoading(false);}}
  async function refresh(silent=false){if(!canView)return;setRefreshing(true);if(!silent)setError('');try{const result=await request<CatalogResult>('/template-catalog/refresh',{method:'POST',headers:{'X-CSRF-Token':token},body:'{}'});setCatalog(result);}catch(reason){try{setCatalog(await request<CatalogResult>('/template-catalog'));}catch{/* retain the last rendered state */}if(!silent)setError(reason instanceof Error?reason.message:'Official catalog refresh failed');}finally{setRefreshing(false);}}
  useEffect(()=>{void load().then(()=>refresh(true));},[canView]);
  if(manage)return <section><button className="quiet library-back" onClick={()=>setManage(false)}><ArrowLeft/>Back to Game Library</button><LegacyTemplatesPage token={token} capabilities={capabilities} onOpenServer={openServer}/></section>;
  if(selected&&provisioning&&(selected.source_type==='official'||selected.source_type==='builtin')&&selected.launch?.resolver==='neoforge')return <NeoForgeAdopt template={selected} token={token} onBack={()=>setProvisioning(false)} onOpenServer={openServer}/>;
  if(selected&&provisioning)return <TemplateProvisionWizard template={selected} token={token} capabilities={capabilities} tenants={creatableTenants} onBack={()=>setProvisioning(false)} onOpenServer={openServer}/>;
  if(selected)return <section><PageHeader eyebrow={sourceLabel(selected.source_type)} title={selected.name} description={selected.description||'Game template'} actions={<><button className="quiet" onClick={()=>setSelected(undefined)}><ArrowLeft/>Back</button>{(selected.launch?.resolver==='neoforge'?canCreateAdopt:canCreateManaged)&&hasProvisionablePath(selected)&&<button onClick={()=>setProvisioning(true)}>Create server</button>}</>}/><TemplatePreview template={selected}/></section>;
  if(!canView)return <EmptyState icon={Package} title="Game Library unavailable" description="Templates.View is required to browse and use templates."/>;
  const items=[...catalog.templates,...personal],categories=[...new Set(items.map(item=>item.category).filter((value):value is string=>Boolean(value)))].sort();
  const visible=filterLibrary(items,query,source,category);
  return <section className="game-library">
    <PageHeader eyebrow="Templates" title="Game Library" description="Create servers from validated GameNode Official templates or your imported Eggs." actions={<>{canManage&&<button className="quiet" onClick={()=>setManage(true)}><Upload/>Imported templates</button>}<button onClick={()=>refresh(false)} disabled={refreshing}><RefreshCw className={refreshing?'spin':''}/>{refreshing?'Refreshing…':'Refresh'}</button></>}/>
    {error&&<p className="error notice">{error}</p>}
    <div className={`catalog-state ${catalog.status.offline?'catalog-state--offline':''}`}>{catalog.status.offline?<WifiOff/>:<Package/>}<span><strong>{catalogStatusLabel(catalog.status)}</strong>{catalog.status.fetched_at&&<small>Last successful fetch {new Date(catalog.status.fetched_at).toLocaleString()}</small>}{catalog.status.invalid_templates>0&&<small>{catalog.status.invalid_templates} invalid template{catalog.status.invalid_templates===1?' was':'s were'} isolated</small>}</span></div>
    <div className="library-toolbar"><label className="library-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search games…" aria-label="Search games"/></label><select value={source} onChange={event=>setSource(event.target.value)} aria-label="Template source"><option value="all">All sources</option><option value="official">Official</option><option value="pelican-pterodactyl">Imported</option><option value="builtin">Local</option></select><select value={category} onChange={event=>setCategory(event.target.value)} aria-label="Category"><option value="all">All categories</option>{categories.map(value=><option key={value} value={value}>{value.charAt(0).toUpperCase()+value.slice(1)}</option>)}</select></div>
    {loading?<SkeletonCards count={6} label="Loading Game Library…" />:items.length===0?<EmptyState icon={catalog.status.offline?WifiOff:Package} title={catalog.status.offline?'Official catalog unavailable':'No games available'} description={catalog.status.offline?'GitHub could not be reached and no valid catalog cache exists. Imported templates remain available.':'Refresh the Official catalog or import a Pelican/Pterodactyl Egg.'} action={canManage?<button onClick={()=>setManage(true)}>Import Egg</button>:undefined}/>:visible.length===0?<EmptyState icon={Search} title="No matching games" description="Try another search or filter."/>:<div className="library-grid">{visible.map(template=><article key={`${template.source_type}-${template.id}`} className="game-card"><div className="game-card__top"><span className="game-card__icon"><Package/></span><span className={`source-badge source-badge--${template.source_type==='official'?'official':'personal'}`}>{sourceLabel(template.source_type)}</span></div><div><h2>{template.name}</h2><p>{template.description||'No description provided.'}</p></div><div className="game-card__meta"><span>{versionLabel(template.version)}</span><span>{template.installer.type==='steamcmd'?'SteamCMD':template.launch?.resolver==='neoforge'?'Java · NeoForge':template.installer.type}</span>{template.platforms?.map(platform=><span key={platform}>{platform}</span>)}</div><div className="template-card__compatibility"><CompatibilityBadge status={(template.native_compatibility??template.compatibility).status}/>{template.container_compatibility&&<CompatibilityBadge status={template.container_compatibility.status}/>}</div><div className="game-card__actions"><button className="quiet" onClick={()=>setSelected(template)}>View</button>{(template.launch?.resolver==='neoforge'?canCreateAdopt:canCreateManaged)&&<button onClick={()=>{setSelected(template);setProvisioning(true);}} disabled={!hasProvisionablePath(template)}>Create server</button>}</div></article>)}</div>}
  </section>;
}
