import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, CircleAlert, HardDriveDownload, LoaderCircle, Play, XCircle } from 'lucide-react';
import { hasCapability } from './capabilities';
import { PageHeader, SectionHeader } from './ui';
import { editableTemplateValues, provisioningStatusLabel, provisioningTerminal, safeDirectoryName, steamCMDReview, templateInputType, templatePortValue, validateTemplateValue } from './templates-helpers';
import { resolveTenantSelection, type TenantOption } from './tenants-helpers';

type Variable={name:string;description?:string;key:string;default_value:string;user_editable:boolean;type:string;sensitive:boolean;required:boolean;nullable:boolean;placeholder?:string;advanced?:boolean;group?:string;validation:{min?:number;max?:number;min_length?:number;max_length?:number;allowed?:string[]}};
type TemplatePort={name:string;protocol:string;port?:number;container_port?:number;variable?:string;offset?:number;required?:boolean;purpose?:string};
type Compatibility={status:'compatible'|'partially_compatible'|'unsupported'|'blocked_by_image_policy';findings:{severity:string;code:string;summary:string}[]};
type ContainerRuntimePlan={images:string[];installer_image:string;startup_template:string;startup_shell:string;resource_defaults?:{memory_limit_bytes?:number;cpu_limit_millis?:number;pids_limit?:number;temp_size_bytes?:number}};
export type ProvisionTemplate={id?:string;name:string;description:string;platforms?:string[];installer:{type:string;steamcmd?:{app_id:number;validate:boolean;login_mode:string}};variables:Variable[];ports?:TemplatePort[];requirements?:{type:string;level:string;value?:string;description:string}[];expected_files?:{path:string;type:string;required:boolean;platform?:string}[];compatibility?:Compatibility;native_compatibility?:Compatibility;container_compatibility?:Compatibility;container_runtime?:ContainerRuntimePlan};
type Job={id:string;template_name:string;server_name:string;directory_name:string;installer_type:string;runtime_type?:string;selected_image?:string;selected_image_digest?:string;status:string;summary:string;error_summary?:string;files_may_remain:boolean;server_id?:string;installer_output?:string[];output_truncated?:boolean};
type Provisionability={provisionable:boolean;host_platform:string;code?:string;summary:string;installer:string;app_id?:number;validate?:boolean;launch_executable?:string;native_compatibility:Compatibility;container_compatibility:Compatibility;container_images?:string[];container_image_policy?:string[]};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(init?.headers??{})},...init});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message??'Request failed')};return response.status===204?undefined as T:response.json()}

export function TemplateProvisionWizard({template,token,capabilities,tenants,onBack,onOpenServer}:{template:ProvisionTemplate;token:string;capabilities?:string[];tenants?:TenantOption[];onBack:()=>void;onOpenServer:(id:string)=>void}){
 const selection=resolveTenantSelection(tenants??[]);
 const [availability,setAvailability]=useState<Provisionability>();const [step,setStep]=useState(1);const [name,setName]=useState(template.name);const [directory,setDirectory]=useState(safeDirectoryName(template.name));const [tenantID,setTenantID]=useState(selection.preselected);const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(template.variables.map(v=>[v.key,v.default_value])));const [runtimeType,setRuntimeType]=useState<'native'|'container'>('native');const [selectedImage,setSelectedImage]=useState(template.container_runtime?.images[0]??'');const [memory,setMemory]=useState(String(template.container_runtime?.resource_defaults?.memory_limit_bytes??1073741824));const [cpu,setCPU]=useState(String(template.container_runtime?.resource_defaults?.cpu_limit_millis??1000));const [job,setJob]=useState<Job>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{api<Provisionability>(`/templates/${template.id}/provisionability`).then(result=>{setAvailability(result);if(result.native_compatibility.status==='unsupported'&&result.container_compatibility.status!=='unsupported'&&result.container_compatibility.status!=='blocked_by_image_policy')setRuntimeType('container');setSelectedImage(result.container_images?.[0]??template.container_runtime?.images[0]??'')}).catch(reason=>setError(reason.message))},[template.id,template.container_runtime?.images]);
 useEffect(()=>{if(!job||provisioningTerminal(job.status))return;const timer=window.setInterval(()=>api<Job>(`/provisioning/jobs/${job.id}`).then(setJob).catch(reason=>setError(reason.message)),1000);return()=>window.clearInterval(timer)},[job?.id,job?.status]);
 const editable=useMemo(()=>template.variables.filter(variable=>variable.user_editable).sort((left,right)=>Number(left.advanced)-Number(right.advanced)||(left.group??'').localeCompare(right.group??'')||left.name.localeCompare(right.name)),[template.variables]);const validation=Object.fromEntries(editable.map(variable=>[variable.key,validateTemplateValue(variable,values[variable.key]??'')]).filter(([,message])=>message));
 const variableGroups=useMemo(()=>Object.entries(editable.reduce<Record<string,Variable[]>>((groups,variable)=>{const group=variable.group||(variable.advanced?'Advanced':'Server');(groups[group]??=[]).push(variable);return groups},{})),[editable]);
 const review=availability&&runtimeType==='native'&&template.installer.type==='steamcmd'?steamCMDReview({appID:availability.app_id??template.installer.steamcmd?.app_id??0,platform:availability.host_platform,validate:availability.validate??template.installer.steamcmd?.validate??false,executable:availability.launch_executable??'Unknown'}):[];
 const containerAvailable=!!availability&&availability.container_compatibility.status!=='unsupported'&&availability.container_compatibility.status!=='blocked_by_image_policy'&&(availability.container_images?.length??0)>0;
 const selectedRuntimeAvailable=runtimeType==='container'?containerAvailable:!!availability?.provisionable&&availability.native_compatibility.status!=='unsupported';
 async function provision(recoverExisting?:unknown){try{setBusy(true);setError('');setJob(await api<Job>(`/templates/${template.id}/provision`,{method:'POST',headers:{'X-CSRF-Token':token},body:JSON.stringify({server_name:name,directory_name:directory,tenant_id:tenantID,variables:editableTemplateValues(template.variables,values),recover_existing:recoverExisting===true,runtime_type:runtimeType,image:runtimeType==='container'?selectedImage:undefined,memory_limit_bytes:runtimeType==='container'?Number(memory):undefined,cpu_limit_millis:runtimeType==='container'?Number(cpu):undefined})}))}catch(reason){setError(reason instanceof Error?reason.message:'Provisioning could not start')}finally{setBusy(false)}}
 async function cancel(){if(!job)return;try{setJob(await api<Job>(`/provisioning/jobs/${job.id}/cancel`,{method:'POST',headers:{'X-CSRF-Token':token}}))}catch(reason){setError(reason instanceof Error?reason.message:'Cancellation failed')}}
 async function startServer(){if(!job?.server_id)return;try{await api(`/servers/${job.server_id}/start`,{method:'POST',headers:{'X-CSRF-Token':token}});onOpenServer(job.server_id)}catch(reason){setError(reason instanceof Error?reason.message:'Server could not start')}}
 if(!availability)return <section><PageHeader eyebrow="Game Library" title={`Create ${template.name}`} description="Checking Native and Container compatibility…" actions={<button className="quiet" onClick={onBack}><ArrowLeft/>Back</button>}/>{error?<p className="error notice">{error}</p>:<div className="panel provision-progress"><LoaderCircle className="spin"/><p>Checking provisionability</p></div>}</section>;
 if(!selectedRuntimeAvailable)return <section><PageHeader eyebrow="Game Library" title={`Create ${template.name}`} description="This runtime cannot be provisioned safely on this host." actions={<button className="quiet" onClick={onBack}><ArrowLeft/>Back</button>}/><div className="notice notice--warning"><strong>{runtimeType==='container'?'Container':'Native'} runtime · {availability.host_platform}</strong><br/>{runtimeType==='container'?availability.container_compatibility.findings.map(f=>f.summary).join(' '):availability.summary}</div><div className="actions"><button className="quiet" onClick={()=>setRuntimeType(runtimeType==='native'?'container':'native')} disabled={runtimeType==='native'&&!containerAvailable||runtimeType==='container'&&!availability.provisionable}>{runtimeType==='native'?'Try Container runtime':'Try Native runtime'}</button></div></section>;
 if(job){const terminal=provisioningTerminal(job.status);const output=job.installer_output??[];return <section><PageHeader eyebrow="Create server · Step 5 of 5" title={job.server_name} description={`${job.template_name} · ${job.directory_name}`} actions={terminal?<button className="quiet" onClick={onBack}><ArrowLeft/>Game Library</button>:undefined}/>{error&&<p className="error notice">{error}</p>}<div className={`panel provision-progress provision-progress--${job.status}`}>{job.status==='completed'?<CheckCircle2/>:job.status==='failed'||job.status==='cancelled'?<XCircle/>:<LoaderCircle className="spin"/>}<p className="eyebrow">{provisioningStatusLabel(job.status)}</p><h2>{job.summary}</h2>{job.runtime_type==='container'&&<p className="muted">Container runtime{job.selected_image?` · ${job.selected_image}`:''}{job.selected_image_digest?` · ${job.selected_image_digest}`:''}</p>}{job.error_summary&&<p className="error">{job.error_summary}</p>}{(job.installer_type==='steamcmd'||job.runtime_type==='container')&&<section className="provision-output"><header><strong>{job.runtime_type==='container'?'Installer container output':'SteamCMD output'}</strong><small>Installer output is bounded, redacted for sensitive values, and retained only in memory until GameNode restarts.</small></header><pre>{output.length?output.join('\n'):'Waiting for installer output…'}</pre>{job.output_truncated&&<p className="notice notice--warning">Output limit reached; earlier installer output remains visible.</p>}</section>}{job.files_may_remain&&<p className="notice notice--warning">Files may remain in the managed target. GameNode did not create a normal server record unless completion succeeded.</p>}<div className="actions">{!terminal&&<button className="danger quiet" onClick={cancel}>Cancel provisioning</button>}{job.status==='failed'&&job.files_may_remain&&<button onClick={()=>provision(true)} disabled={busy}>Register installed server</button>}{job.status==='completed'&&job.server_id&&<><button onClick={()=>onOpenServer(job.server_id!)}>Open server</button>{hasCapability(capabilities,'Server.Start')&&<button className="quiet" onClick={startServer}><Play/>Start server</button>}</>}</div></div></section>}
 return <section><PageHeader eyebrow={`Create server · Step ${step} of 5`} title={template.name} description={['Server basics','Configuration','Installation','Review'][step-1]} actions={<button className="quiet" onClick={onBack}><ArrowLeft/>Back</button>}/>{error&&<p className="error notice">{error}</p>}
 {step===1&&<form className="panel provision-form" onSubmit={(event:FormEvent)=>{event.preventDefault();setStep(2)}}><SectionHeader title="Server basics" description="The folder is created below GameNode's managed server storage."/>{selection.locked?<label>Tenant<input value={tenants?.find(t=>t.id===tenantID)?.name??tenantID} readOnly disabled/></label>:<label>Tenant<select value={tenantID} required onChange={event=>setTenantID(event.target.value)}><option value="">Choose tenant…</option>{(tenants??[]).map(tenant=><option key={tenant.id} value={tenant.id}>{tenant.name}</option>)}</select></label>}<label>Server name<input value={name} maxLength={100} required onChange={event=>setName(event.target.value)}/></label><label>Managed folder name<input value={directory} pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,63}" required onChange={event=>setDirectory(event.target.value)}/><small>No absolute paths or traversal. Existing populated folders are refused.</small></label><button disabled={!tenantID}>Continue to configuration</button></form>}
 {step===2&&<form className="panel provision-form" onSubmit={(event:FormEvent)=>{event.preventDefault();if(!Object.keys(validation).length)setStep(3)}}><SectionHeader title="Configuration" description="Values are validated server-side and substituted only into explicitly allowed fields."/>{variableGroups.map(([group,variables])=><div className="definition-list" key={group}><strong>{group}</strong>{(variables??[]).map(variable=><label key={variable.key}>{variable.name}{variable.required&&' *'}{variable.validation.allowed?.length?<select value={values[variable.key]??''} onChange={event=>setValues({...values,[variable.key]:event.target.value})}>{variable.validation.allowed.map(value=><option key={value}>{value}</option>)}</select>:templateInputType(variable.type,variable.sensitive)==='checkbox'?<input type="checkbox" checked={values[variable.key]==='1'||values[variable.key]==='true'} onChange={event=>setValues({...values,[variable.key]:event.target.checked?'1':'0'})}/>:<input type={templateInputType(variable.type,variable.sensitive)} value={values[variable.key]??''} placeholder={variable.placeholder} min={variable.validation.min} max={variable.validation.max} minLength={variable.validation.min_length} maxLength={variable.validation.max_length} required={variable.required&&!variable.nullable} onChange={event=>setValues({...values,[variable.key]:event.target.value})}/>}<small>{variable.description}{validation[variable.key]&&<span className="error"> · {validation[variable.key]}</span>}</small></label>)}</div>)}{!!template.ports?.length&&<div className="notice"><strong>Ports</strong><br/>{template.ports.map(port=>`${port.name}: ${port.protocol.toUpperCase()} ${templatePortValue(port,values)}`).join(' · ')}</div>}<div className="actions"><button type="button" className="quiet" onClick={()=>setStep(1)}>Back</button><button disabled={!!Object.keys(validation).length}>Installation</button></div></form>}
 {step===3&&<section className="panel provision-review"><SectionHeader title="Installation" description="Choose the explicit runtime. Container Egg installation is isolated from the GameNode host."/><div className="runtime-choice"><label><input type="radio" name="runtime" checked={runtimeType==='native'} onChange={()=>setRuntimeType('native')} disabled={!availability.provisionable||availability.native_compatibility.status==='unsupported'}/> Native <small>{availability.native_compatibility.status}</small></label><label><input type="radio" name="runtime" checked={runtimeType==='container'} onChange={()=>setRuntimeType('container')} disabled={!containerAvailable}/> Container <small>{availability.container_compatibility.status}</small></label></div>{runtimeType==='container'?<div className="container-provision-options"><label>Game image<select value={selectedImage} onChange={event=>setSelectedImage(event.target.value)}>{(availability.container_images??[]).map(image=><option key={image} value={image}>{image}</option>)}</select><small>Only declared images allowed by the node registry policy can be selected.</small></label><div className="form-grid"><label>Memory limit (bytes)<input type="number" min="16777216" value={memory} onChange={event=>setMemory(event.target.value)}/></label><label>CPU limit (millicores)<input type="number" min="10" value={cpu} onChange={event=>setCPU(event.target.value)}/></label></div><div className="notice">Installer image: <code>{template.container_runtime?.installer_image}</code>. Egg install/start commands run inside a short-lived unprivileged container with only the managed server root mounted.</div></div>:<dl>{review.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>}{!!template.requirements?.length&&<div className="notice"><strong>Requirements</strong>{template.requirements.map((requirement,index)=><p key={`${requirement.type}-${index}`}><strong>{requirement.level==='hard'?'Required':'Information'} · {requirement.type}{requirement.value?` (${requirement.value})`:''}</strong><br/>{requirement.description}</p>)}</div>}<div className="actions"><button className="quiet" onClick={()=>setStep(2)}>Back</button><button onClick={()=>setStep(4)} disabled={runtimeType==='container'&&!selectedImage}>Continue to review</button></div></section>}
 {step===4&&<section className="panel provision-review"><SectionHeader title="Review" description={runtimeType==='container'?'The Egg script runs only inside the controlled installer container; no host shell or credentials are used.':'Native installation uses structured process data and does not execute Egg scripts.'}/><dl><div><dt>Runtime</dt><dd>{runtimeType==='container'?'Container':'Native'}</dd></div>{runtimeType==='container'&&<><div><dt>Image</dt><dd><code>{selectedImage}</code></dd></div><div><dt>Resources</dt><dd>{memory} bytes · {cpu} millicores</dd></div></> }<div><dt>Tenant</dt><dd>{tenants?.find(t=>t.id===tenantID)?.name??tenantID}</dd></div><div><dt>Server</dt><dd>{name}</dd></div><div><dt>Managed folder</dt><dd>{directory}</dd></div>{review.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}<div><dt>Configuration</dt><dd>{editable.length} values; sensitive values hidden</dd></div><div><dt>Ports</dt><dd>{template.ports?.map(port=>`${port.protocol.toUpperCase()} ${templatePortValue(port,values)}`).join(', ')||'None declared'}</dd></div><div><dt>Validation</dt><dd>{template.expected_files?.filter(file=>file.required).length??0} required installation artifacts</dd></div></dl><div className="notice"><CircleAlert/>Installation may leave files in the target if the installer fails. No server record is created before installation and artifact verification succeed.</div><div className="actions"><button className="quiet" onClick={()=>setStep(3)}>Back</button><button onClick={provision} disabled={busy}><HardDriveDownload/>{busy?'Starting…':'Install and create server'}</button></div></section>}</section>
}
