import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, CircleAlert, HardDriveDownload, LoaderCircle, Play, XCircle } from 'lucide-react';
import { hasCapability } from './capabilities';
import { PageHeader, SectionHeader } from './ui';
import { editableTemplateValues, provisioningStatusLabel, provisioningTerminal, safeDirectoryName, steamCMDReview, templateInputType, templatePortValue, validateTemplateValue } from './templates-helpers';

type Variable={name:string;description?:string;key:string;default_value:string;user_editable:boolean;type:string;sensitive:boolean;required:boolean;nullable:boolean;placeholder?:string;advanced?:boolean;group?:string;validation:{min?:number;max?:number;min_length?:number;max_length?:number;allowed?:string[]}};
type TemplatePort={name:string;protocol:string;port?:number;variable?:string;offset?:number;required?:boolean;purpose?:string};
export type ProvisionTemplate={id?:string;name:string;description:string;platforms?:string[];installer:{type:string;steamcmd?:{app_id:number;validate:boolean;login_mode:string}};variables:Variable[];ports?:TemplatePort[];requirements?:{type:string;level:string;value?:string;description:string}[];expected_files?:{path:string;type:string;required:boolean;platform?:string}[]};
type Job={id:string;template_name:string;server_name:string;directory_name:string;installer_type:string;status:string;summary:string;error_summary?:string;files_may_remain:boolean;server_id?:string;installer_output?:string[];output_truncated?:boolean};
type Provisionability={provisionable:boolean;host_platform:string;code?:string;summary:string;installer:string;app_id?:number;validate?:boolean;launch_executable?:string};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(init?.headers??{})},...init});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message??'Request failed')};return response.status===204?undefined as T:response.json()}

export function TemplateProvisionWizard({template,token,capabilities,onBack,onOpenServer}:{template:ProvisionTemplate;token:string;capabilities?:string[];onBack:()=>void;onOpenServer:(id:string)=>void}){
 const [availability,setAvailability]=useState<Provisionability>();const [step,setStep]=useState(1);const [name,setName]=useState(template.name);const [directory,setDirectory]=useState(safeDirectoryName(template.name));const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(template.variables.map(v=>[v.key,v.default_value])));const [job,setJob]=useState<Job>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{api<Provisionability>(`/templates/${template.id}/provisionability`).then(setAvailability).catch(reason=>setError(reason.message))},[template.id]);
 useEffect(()=>{if(!job||provisioningTerminal(job.status))return;const timer=window.setInterval(()=>api<Job>(`/provisioning/jobs/${job.id}`).then(setJob).catch(reason=>setError(reason.message)),1000);return()=>window.clearInterval(timer)},[job?.id,job?.status]);
 const editable=useMemo(()=>template.variables.filter(variable=>variable.user_editable).sort((left,right)=>Number(left.advanced)-Number(right.advanced)||(left.group??'').localeCompare(right.group??'')||left.name.localeCompare(right.name)),[template.variables]);const validation=Object.fromEntries(editable.map(variable=>[variable.key,validateTemplateValue(variable,values[variable.key]??'')]).filter(([,message])=>message));
 const variableGroups=useMemo(()=>Object.entries(editable.reduce<Record<string,Variable[]>>((groups,variable)=>{const group=variable.group||(variable.advanced?'Advanced':'Server');(groups[group]??=[]).push(variable);return groups},{})),[editable]);
 const review=availability&&template.installer.type==='steamcmd'?steamCMDReview({appID:availability.app_id??template.installer.steamcmd?.app_id??0,platform:availability.host_platform,validate:availability.validate??template.installer.steamcmd?.validate??false,executable:availability.launch_executable??'Unknown'}):[];
 async function provision(recoverExisting?:unknown){try{setBusy(true);setError('');setJob(await api<Job>(`/templates/${template.id}/provision`,{method:'POST',headers:{'X-CSRF-Token':token},body:JSON.stringify({server_name:name,directory_name:directory,variables:editableTemplateValues(template.variables,values),recover_existing:recoverExisting===true})}))}catch(reason){setError(reason instanceof Error?reason.message:'Provisioning could not start')}finally{setBusy(false)}}
 async function cancel(){if(!job)return;try{setJob(await api<Job>(`/provisioning/jobs/${job.id}/cancel`,{method:'POST',headers:{'X-CSRF-Token':token}}))}catch(reason){setError(reason instanceof Error?reason.message:'Cancellation failed')}}
 async function startServer(){if(!job?.server_id)return;try{await api(`/servers/${job.server_id}/start`,{method:'POST',headers:{'X-CSRF-Token':token}});onOpenServer(job.server_id)}catch(reason){setError(reason instanceof Error?reason.message:'Server could not start')}}
 if(!availability)return <section><PageHeader eyebrow="Game Library" title={`Create ${template.name}`} description="Checking native host compatibility…" actions={<button className="quiet" onClick={onBack}><ArrowLeft/>Back</button>}/>{error?<p className="error notice">{error}</p>:<div className="panel provision-progress"><LoaderCircle className="spin"/><p>Checking provisionability</p></div>}</section>;
 if(!availability.provisionable)return <section><PageHeader eyebrow="Game Library" title={`Create ${template.name}`} description="This template cannot be provisioned safely on this host." actions={<button className="quiet" onClick={onBack}><ArrowLeft/>Back</button>}/><div className="notice notice--warning"><strong>{availability.host_platform} host{availability.code?` · ${availability.code}`:''}</strong><br/>{availability.summary}</div></section>;
 if(job){const terminal=provisioningTerminal(job.status);const output=job.installer_output??[];return <section><PageHeader eyebrow="Create server · Step 5 of 5" title={job.server_name} description={`${job.template_name} · ${job.directory_name}`} actions={terminal?<button className="quiet" onClick={onBack}><ArrowLeft/>Game Library</button>:undefined}/>{error&&<p className="error notice">{error}</p>}<div className={`panel provision-progress provision-progress--${job.status}`}>{job.status==='completed'?<CheckCircle2/>:job.status==='failed'||job.status==='cancelled'?<XCircle/>:<LoaderCircle className="spin"/>}<p className="eyebrow">{provisioningStatusLabel(job.status)}</p><h2>{job.summary}</h2>{job.error_summary&&<p className="error">{job.error_summary}</p>}{job.installer_type==='steamcmd'&&<section className="provision-output"><header><strong>SteamCMD output</strong><small>Installer output is kept only in memory and is cleared when GameNode restarts. SteamCMD may send progress lines in batches.</small></header><pre>{output.length?output.join('\n'):'Waiting for SteamCMD output…'}</pre>{job.output_truncated&&<p className="notice notice--warning">Output limit reached; earlier installer output remains visible.</p>}</section>}{job.files_may_remain&&<p className="notice notice--warning">Files may remain in the managed target. GameNode did not create a normal server record unless completion succeeded.</p>}<div className="actions">{!terminal&&<button className="danger quiet" onClick={cancel}>Cancel provisioning</button>}{job.status==='failed'&&job.files_may_remain&&<button onClick={()=>provision(true)} disabled={busy}>Register installed server</button>}{job.status==='completed'&&job.server_id&&<><button onClick={()=>onOpenServer(job.server_id!)}>Open server</button>{hasCapability(capabilities,'Server.Start')&&<button className="quiet" onClick={startServer}><Play/>Start server</button>}</>}</div></div></section>}
 return <section><PageHeader eyebrow={`Create server · Step ${step} of 5`} title={template.name} description={['Server basics','Configuration','Installation','Review'][step-1]} actions={<button className="quiet" onClick={onBack}><ArrowLeft/>Back</button>}/>{error&&<p className="error notice">{error}</p>}
 {step===1&&<form className="panel provision-form" onSubmit={(event:FormEvent)=>{event.preventDefault();setStep(2)}}><SectionHeader title="Server basics" description="The folder is created below GameNode's managed server storage."/><label>Server name<input value={name} maxLength={100} required onChange={event=>setName(event.target.value)}/></label><label>Managed folder name<input value={directory} pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,63}" required onChange={event=>setDirectory(event.target.value)}/><small>No absolute paths or traversal. Existing populated folders are refused.</small></label><button>Continue to configuration</button></form>}
 {step===2&&<form className="panel provision-form" onSubmit={(event:FormEvent)=>{event.preventDefault();if(!Object.keys(validation).length)setStep(3)}}><SectionHeader title="Configuration" description="Values are validated server-side and substituted only into explicitly allowed fields."/>{variableGroups.map(([group,variables])=><div className="definition-list" key={group}><strong>{group}</strong>{(variables??[]).map(variable=><label key={variable.key}>{variable.name}{variable.required&&' *'}{variable.validation.allowed?.length?<select value={values[variable.key]??''} onChange={event=>setValues({...values,[variable.key]:event.target.value})}>{variable.validation.allowed.map(value=><option key={value}>{value}</option>)}</select>:templateInputType(variable.type,variable.sensitive)==='checkbox'?<input type="checkbox" checked={values[variable.key]==='1'||values[variable.key]==='true'} onChange={event=>setValues({...values,[variable.key]:event.target.checked?'1':'0'})}/>:<input type={templateInputType(variable.type,variable.sensitive)} value={values[variable.key]??''} placeholder={variable.placeholder} min={variable.validation.min} max={variable.validation.max} minLength={variable.validation.min_length} maxLength={variable.validation.max_length} required={variable.required&&!variable.nullable} onChange={event=>setValues({...values,[variable.key]:event.target.value})}/>}<small>{variable.description}{validation[variable.key]&&<span className="error"> · {validation[variable.key]}</span>}</small></label>)}</div>)}{!!template.ports?.length&&<div className="notice"><strong>Ports</strong><br/>{template.ports.map(port=>`${port.name}: ${port.protocol.toUpperCase()} ${templatePortValue(port,values)}`).join(' · ')}</div>}<div className="actions"><button type="button" className="quiet" onClick={()=>setStep(1)}>Back</button><button disabled={!!Object.keys(validation).length}>Installation</button></div></form>}
 {step===3&&<section className="panel provision-review"><SectionHeader title="Installation" description="Installer metadata is fixed by the selected Official Template, not entered as free-form commands."/><dl>{review.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>{!!template.requirements?.length&&<div className="notice"><strong>Requirements</strong>{template.requirements.map((requirement,index)=><p key={`${requirement.type}-${index}`}><strong>{requirement.level==='hard'?'Required':'Information'} · {requirement.type}{requirement.value?` (${requirement.value})`:''}</strong><br/>{requirement.description}</p>)}</div>}<div className="actions"><button className="quiet" onClick={()=>setStep(2)}>Back</button><button onClick={()=>setStep(4)}>Continue to review</button></div></section>}
 {step===4&&<section className="panel provision-review"><SectionHeader title="Review" description="No Egg script, shell, Docker image, credentials, or free-form SteamCMD flags will run."/><dl><div><dt>Server</dt><dd>{name}</dd></div><div><dt>Managed folder</dt><dd>{directory}</dd></div>{review.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}<div><dt>Configuration</dt><dd>{editable.length} values; sensitive values hidden</dd></div><div><dt>Ports</dt><dd>{template.ports?.map(port=>`${port.protocol.toUpperCase()} ${templatePortValue(port,values)}`).join(', ')||'None declared'}</dd></div><div><dt>Validation</dt><dd>{template.expected_files?.filter(file=>file.required).length??0} required installation artifacts</dd></div></dl><div className="notice"><CircleAlert/>Installation may leave files in the target if SteamCMD fails. No server record is created before installation and artifact verification succeed.</div><div className="actions"><button className="quiet" onClick={()=>setStep(3)}>Back</button><button onClick={provision} disabled={busy}><HardDriveDownload/>{busy?'Starting…':'Install and create server'}</button></div></section>}</section>
}
