import { ChangeEvent, useEffect, useState } from 'react';
import { ArrowLeft, FileJson, Package, ShieldAlert, Trash2, Upload } from 'lucide-react';
import { hasCapability } from './capabilities';
import { EmptyState, PageHeader, SectionHeader } from './ui';
import { compatibilityLabel, compatibilityTone, maskTemplateDefault, validateEggFile, variableTypeLabel, type CompatibilityStatus } from './templates-helpers';
import { TemplateProvisionWizard } from './template-provision';
import './templates.css';

type Finding = { severity: 'info' | 'warning' | 'error'; component: string; code: string; summary: string };
type Variable = { name: string; description?: string; key: string; default_value: string; user_viewable: boolean; user_editable: boolean; type: string; sensitive: boolean; required: boolean; nullable: boolean; validation: { min?: number; max?: number; allowed?: string[] }; raw_rules?: string[] };
type Template = { id?: string; name: string; description: string; source_type: string; source_identifier?: string; source_format_version?: string; source_metadata: { author?: string; docker_images?: Record<string, string> }; installer: { type: string; steamcmd?: { app_id: number; validate: boolean; login_mode: string; platform: string; beta_branch_variable?: string; beta_password_variable?: string; install_target: string } }; launch?: { executable: string; arguments: string[]; working_root: string }; variables: Variable[]; compatibility: { status: CompatibilityStatus; findings: Finding[] } };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/v1${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, ...init });
  if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.error?.message ?? 'Request failed'); }
  return response.status === 204 ? undefined as T : response.json();
}

function CompatibilityBadge({ status }: { status: CompatibilityStatus }) { return <span className={`template-status template-status--${compatibilityTone(status)}`}>{compatibilityLabel(status)}</span>; }

function TemplatePreview({ template }: { template: Template }) {
  return <div className="template-preview">
    <section className="subpanel"><SectionHeader title="Template info" description="Normalized provenance from the uploaded Egg" /><div className="template-summary"><div><small>Name</small><strong>{template.name}</strong></div><div><small>Source</small><strong>{template.source_type}</strong></div><div><small>Author</small><strong>{template.source_metadata.author || 'Not provided'}</strong></div><div><small>Compatibility</small><CompatibilityBadge status={template.compatibility.status} /></div></div><p>{template.description || 'No description provided.'}</p></section>
    <section className="subpanel"><SectionHeader title="Compatibility" description="Deterministic findings from GameNode's native-runtime analysis" /><div className="template-summary"><div><small>Installer</small><strong>{template.installer.type === 'steamcmd' ? `SteamCMD · App ${template.installer.steamcmd?.app_id}` : 'Unsupported'}</strong></div><div><small>Startup</small><strong>{template.launch ? 'Structured process extracted' : 'No safe launch plan'}</strong></div><div><small>Variables</small><strong>{template.variables.length} imported</strong></div><div><small>Docker</small><strong>{Object.keys(template.source_metadata.docker_images ?? {}).length ? 'Metadata only' : 'Not declared'}</strong></div></div><div className="finding-list">{template.compatibility.findings.map((finding, index) => <article key={`${finding.code}-${index}`} className={`finding finding--${finding.severity}`}><span>{finding.severity === 'error' ? 'Error' : finding.severity === 'warning' ? 'Warning' : 'Info'}</span><div><strong>{finding.code}</strong><p>{finding.summary}</p></div></article>)}</div></section>
    <section className="subpanel"><SectionHeader title="Variables" description="Typed template schema; sensitive defaults are discarded by the importer" /><div className="variable-list">{template.variables.map(variable => <article key={variable.key}><div><strong>{variable.name || variable.key}</strong><code>{variable.key}</code></div><p>{variable.description || 'No description'}</p><div className="variable-meta"><span>{variableTypeLabel(variable.type)}</span>{variable.required && <span>Required</span>}{variable.nullable && <span>Nullable</span>}{variable.sensitive && <span className="sensitive"><ShieldAlert />Sensitive</span>}<span>Default: {maskTemplateDefault(variable.default_value, variable.sensitive)}</span></div></article>)}</div></section>
  </div>;
}

export function TemplatesPage({ token, capabilities, onOpenServer }: { token: string; capabilities?: string[]; onOpenServer?: (id: string) => void }) {
  const canView = hasCapability(capabilities, 'Templates.View'), canManage = hasCapability(capabilities, 'Templates.Manage');
  const [items, setItems] = useState<Template[]>([]), [preview, setPreview] = useState<Template>(), [source, setSource] = useState<unknown>(), [selected, setSelected] = useState<Template>(), [wizard, setWizard] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [provisioning,setProvisioning]=useState(false);
  const load = () => canView ? request<{ templates: Template[] }>('/templates').then(result => setItems(result.templates)).catch(reason => setError(reason.message)) : Promise.resolve();
  useEffect(() => { load(); }, [canView]);
  async function upload(event: ChangeEvent<HTMLInputElement>) { setError(''); setPreview(undefined); setSource(undefined); const file = event.target.files?.[0]; if (!file) return; const validation = validateEggFile(file.name, file.size); if (validation) { setError(validation); return; } try { const parsed = JSON.parse(await file.text()); setSource(parsed); setBusy(true); setPreview(await request<Template>('/templates/analyze/egg', { method: 'POST', headers: { 'X-CSRF-Token': token }, body: JSON.stringify({ egg: parsed }) })); } catch (reason) { setError(reason instanceof SyntaxError ? 'The selected file is not valid JSON.' : reason instanceof Error ? reason.message : 'Egg analysis failed'); } finally { setBusy(false); } }
  async function importTemplate() { if (!source) return; try { setBusy(true); await request<Template>('/templates/import/egg', { method: 'POST', headers: { 'X-CSRF-Token': token }, body: JSON.stringify({ egg: source }) }); setWizard(false); setPreview(undefined); setSource(undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Import failed'); } finally { setBusy(false); } }
  async function remove(template: Template) { if (!template.id) return; try { await request<void>(`/templates/${template.id}`, { method: 'DELETE', headers: { 'X-CSRF-Token': token } }); setSelected(undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Delete failed'); } }
  if (wizard) return <section><PageHeader eyebrow="Templates" title="Import Egg" description="Analyze a Pelican/Pterodactyl Egg before storing a native GameNode template." actions={<button className="quiet" onClick={() => { setWizard(false); setPreview(undefined); setSource(undefined); }}><ArrowLeft />Back</button>} />{error && <p className="error notice">{error}</p>}<section className="panel template-upload"><FileJson /><div><h2>Upload Egg JSON</h2><p>Maximum 256 KiB. Files are analyzed locally by GameNode; URL import is not supported.</p></div><label className="upload-button"><Upload />Choose JSON<input type="file" accept="application/json,.json" onChange={upload} disabled={busy} /></label></section>{busy && <p className="notice">Analyzing Egg…</p>}{preview && <><TemplatePreview template={preview} /><div className="template-import-actions"><button className="quiet" onClick={() => { setPreview(undefined); setSource(undefined); }}>Choose another file</button><button onClick={importTemplate} disabled={busy}><Package />Import template</button></div></>}</section>;
  if (selected && provisioning) return <TemplateProvisionWizard template={selected} token={token} capabilities={capabilities} onBack={() => setProvisioning(false)} onOpenServer={onOpenServer ?? ((id) => { sessionStorage.setItem('gamenode:open-server', id); window.dispatchEvent(new Event('gamenode:open-server')); })} />;
  if (selected) return <section><PageHeader eyebrow="Templates" title={selected.name} description={selected.description || 'Imported game template'} actions={<><button className="quiet" onClick={() => setSelected(undefined)}><ArrowLeft />Back</button>{canView && hasCapability(capabilities, 'Server.Create') && <button onClick={() => setProvisioning(true)}>Create server</button>}{canManage && <button className="danger quiet" onClick={() => remove(selected)}><Trash2 />Delete</button>}</>} /><TemplatePreview template={selected} /></section>;
  return <section><PageHeader eyebrow="Library" title="Templates" description="Normalized native GameNode templates imported from Pelican/Pterodactyl Eggs." actions={canManage ? <button onClick={() => { setWizard(true); setError(''); }}><Upload />Import Egg</button> : undefined} />{error && <p className="error notice">{error}</p>}{!canView ? <EmptyState icon={Package} title="Import access only" description="You may analyze and import Eggs, but Templates.View is required to list stored templates." action={canManage ? <button onClick={() => setWizard(true)}>Import Egg</button> : undefined} /> : items.length === 0 ? <EmptyState icon={Package} title="No templates yet" description="Import an Egg to create a normalized GameNode template and compatibility report." action={canManage ? <button onClick={() => setWizard(true)}>Import your first Egg</button> : undefined} /> : <div className="template-grid">{items.map(template => <button key={template.id} className="template-card" onClick={() => setSelected(template)}><span className="template-card__icon"><Package /></span><span><strong>{template.name}</strong><small>{template.source_type} · {template.installer.type}</small></span><CompatibilityBadge status={template.compatibility.status} /></button>)}</div>}</section>;
}
